// Code generated by "stringer -type=DirectoryContentsOrder -linecomment -trimprefix=DirectoryContentsOrder -output directory-contents-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirectoryContentsOrderFoldersFirst-0]
	_ = x[DirectoryContentsOrderFilesFirst-1]
}

const _DirectoryContentsOrder_name = "folders-firstfiles-first"

var _DirectoryContentsOrder_index = [...]uint8{0, 13, 24}

func (i DirectoryContentsOrder) String() string {
	if i >= DirectoryContentsOrder(len(_DirectoryContentsOrder_index)-1) {
		return "DirectoryContentsOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DirectoryContentsOrder_name[_DirectoryContentsOrder_index[i]:_DirectoryContentsOrder_index[i+1]]
}
