// Code generated by "stringer -type=FilterType -linecomment -trimprefix=Filter -output filter-type-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterTypeUndefined-0]
	_ = x[FilterTypeGlobEx-1]
	_ = x[FilterTypeRegex-2]
	_ = x[FilterTypeGlob-3]
	_ = x[FilterTypeCustom-4]
	_ = x[FilterTypePoly-5]
}

const _FilterType_name = "undefined-filterglob-ex-filterregex-filterglob-filtercustom-filterpoly-filter"

var _FilterType_index = [...]uint8{0, 16, 30, 42, 53, 66, 77}

func (i FilterType) String() string {
	if i >= FilterType(len(_FilterType_index)-1) {
		return "FilterType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterType_name[_FilterType_index[i]:_FilterType_index[i+1]]
}
