// Code generated by "stringer -type=InternalRole -linecomment -trimprefix=InternalRole -output internal-role-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InternalRoleRoleUndefined-0]
	_ = x[InternalRoleLogger-1]
	_ = x[InternalRoleSampler-2]
	_ = x[InternalRoleResume-3]
}

const _InternalRole_name = "undefined-rolelogger-rolesampler-roleresume-role"

var _InternalRole_index = [...]uint8{0, 14, 25, 37, 48}

func (i InternalRole) String() string {
	if i >= InternalRole(len(_InternalRole_index)-1) {
		return "InternalRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InternalRole_name[_InternalRole_index[i]:_InternalRole_index[i+1]]
}
