// Code generated by "stringer -type=Metric -linecomment -trimprefix=Metric -output metric-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MetricNoFilesInvoked-0]
	_ = x[MetricNoFilesFilteredOut-1]
	_ = x[MetricNoFoldersInvoked-2]
	_ = x[MetricNoFoldersFilteredOut-3]
	_ = x[MetricNoChildFilesFound-4]
	_ = x[MetricNoChildFilesFilteredOut-5]
}

const _Metric_name = "metric-no-of-filesmetric-no-of-files-filtered-outmetric-no-of-foldersmetric-no-of-folders-filtered-outmetric-no-of-child-files-foundmetric-no-of-child-files-found"

var _Metric_index = [...]uint8{0, 18, 49, 69, 102, 132, 162}

func (i Metric) String() string {
	if i >= Metric(len(_Metric_index)-1) {
		return "Metric(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Metric_name[_Metric_index[i]:_Metric_index[i+1]]
}
