// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"fmt"
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ ActionHasEmptyCmd
//
// ActionHasEmptyCmd indicates that an action with the specified name has an
// empty command string.
// =============================================================================

// ActionHasEmptyCmdTemplData Action has empty cmd string error.
type ActionHasEmptyCmdTemplData struct {
	agenorTemplData
	// Action is the action name that has an empty cmd string
	Action string
}

// Message creates a new i18n message using the template data.
func (td ActionHasEmptyCmdTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "action-has-empty-cmd.dynamic-error",
		Description: "Action has empty cmd string error",
		Other:       "Action has empty cmd string: '{{.Action}}'",
	}
}

// ActionHasEmptyCmdError Action has empty cmd string error.
type ActionHasEmptyCmdError struct {
	li18ngo.LocalisableError
	ActionHasEmptyCmdTemplData
}

// NewActionHasEmptyCmdError creates a new ActionHasEmptyCmdError.
func NewActionHasEmptyCmdError(action string) error {
	td := ActionHasEmptyCmdTemplData{
		agenorTemplData: agenorTemplData{},
		Action:          action,
	}
	return &ActionHasEmptyCmdError{
		LocalisableError:           li18ngo.LocalisableError{Data: td},
		ActionHasEmptyCmdTemplData: td,
	}
}

// =============================================================================
// ❌ ActionNotFound
//
// ActionNotFound indicates that an action with the specified name was not found
// in the traversal configuration.
// =============================================================================

// ActionNotFoundTemplData Action not found in config error.
type ActionNotFoundTemplData struct {
	agenorTemplData
	// Action is the action name that was not found
	Action string
}

// Message creates a new i18n message using the template data.
func (td ActionNotFoundTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "action-not-found.dynamic-error",
		Description: "Action not found in config error",
		Other:       "Action not found: '{{.Action}}'",
	}
}

// ActionNotFoundError Action not found in config error.
type ActionNotFoundError struct {
	li18ngo.LocalisableError
	ActionNotFoundTemplData
}

// NewActionNotFoundError creates a new ActionNotFoundError.
func NewActionNotFoundError(action string) error {
	td := ActionNotFoundTemplData{
		agenorTemplData: agenorTemplData{},
		Action:          action,
	}
	return &ActionNotFoundError{
		LocalisableError:        li18ngo.LocalisableError{Data: td},
		ActionNotFoundTemplData: td,
	}
}

// =============================================================================
// ❌ BedrockLoadDecoding
//
// BedrockLoadDecoding indicates that the configuration could not be decoded
// into the target struct during the bedrock.Load call.
// =============================================================================

// BedrockLoadDecodingErrorTemplData Error returned when config decoding fails
// during bedrock.Load.
type BedrockLoadDecodingErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td BedrockLoadDecodingErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "bedrock-load-decoding.static-error",
		Description: "Error returned when config decoding fails during bedrock.Load",
		Other:       "bedrock.Load: decoding",
	}
}

// BedrockLoadDecodingError Error returned when config decoding fails during
// bedrock.Load.
type BedrockLoadDecodingError struct {
	li18ngo.LocalisableError
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e BedrockLoadDecodingError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e BedrockLoadDecodingError) Unwrap() error {
	return e.wrapped
}

// NewBedrockLoadDecodingError creates a new BedrockLoadDecodingError wrapping
// wrapped.
func NewBedrockLoadDecodingError(wrapped error) error {
	return &BedrockLoadDecodingError{
		LocalisableError: li18ngo.LocalisableError{Data: BedrockLoadDecodingErrorTemplData{}},
		wrapped:          wrapped,
	}
}

// =============================================================================
// ❌ BedrockLoadReadingConfig
//
// BedrockLoadReadingConfig indicates that the configuration file could not be
// read during the bedrock.Load call.
// =============================================================================

// BedrockLoadReadingConfigErrorTemplData Error returned when reading the config
// file fails during bedrock.Load.
type BedrockLoadReadingConfigErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td BedrockLoadReadingConfigErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "bedrock-load-reading-config.static-error",
		Description: "Error returned when reading the config file fails during bedrock.Load",
		Other:       "bedrock.Load: reading config",
	}
}

// BedrockLoadReadingConfigError Error returned when reading the config file
// fails during bedrock.Load.
type BedrockLoadReadingConfigError struct {
	li18ngo.LocalisableError
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e BedrockLoadReadingConfigError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e BedrockLoadReadingConfigError) Unwrap() error {
	return e.wrapped
}

// NewBedrockLoadReadingConfigError creates a new BedrockLoadReadingConfigError
// wrapping wrapped.
func NewBedrockLoadReadingConfigError(wrapped error) error {
	return &BedrockLoadReadingConfigError{
		LocalisableError: li18ngo.LocalisableError{Data: BedrockLoadReadingConfigErrorTemplData{}},
		wrapped:          wrapped,
	}
}

// =============================================================================
// ❌ BedrockLoadValidation
//
// BedrockLoadValidation indicates that the decoded configuration failed
// validation during the bedrock.Load call.
// =============================================================================

// BedrockLoadValidationErrorTemplData Error returned when config validation
// fails during bedrock.Load.
type BedrockLoadValidationErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td BedrockLoadValidationErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "bedrock-load-validation.static-error",
		Description: "Error returned when config validation fails during bedrock.Load",
		Other:       "bedrock.Load: validation",
	}
}

// BedrockLoadValidationError Error returned when config validation fails during
// bedrock.Load.
type BedrockLoadValidationError struct {
	li18ngo.LocalisableError
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e BedrockLoadValidationError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e BedrockLoadValidationError) Unwrap() error {
	return e.wrapped
}

// NewBedrockLoadValidationError creates a new BedrockLoadValidationError
// wrapping wrapped.
func NewBedrockLoadValidationError(wrapped error) error {
	return &BedrockLoadValidationError{
		LocalisableError: li18ngo.LocalisableError{Data: BedrockLoadValidationErrorTemplData{}},
		wrapped:          wrapped,
	}
}

// =============================================================================
// ❌ BedrockLoadViperSetup
//
// BedrockLoadViperSetup indicates that viper could not be configured during the
// bedrock.Load call.
// =============================================================================

// BedrockLoadViperSetupErrorTemplData Error returned when viper setup fails
// during bedrock.Load.
type BedrockLoadViperSetupErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td BedrockLoadViperSetupErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "bedrock-load-viper-setup.static-error",
		Description: "Error returned when viper setup fails during bedrock.Load",
		Other:       "bedrock.Load: viper setup",
	}
}

// BedrockLoadViperSetupError Error returned when viper setup fails during
// bedrock.Load.
type BedrockLoadViperSetupError struct {
	li18ngo.LocalisableError
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e BedrockLoadViperSetupError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e BedrockLoadViperSetupError) Unwrap() error {
	return e.wrapped
}

// NewBedrockLoadViperSetupError creates a new BedrockLoadViperSetupError
// wrapping wrapped.
func NewBedrockLoadViperSetupError(wrapped error) error {
	return &BedrockLoadViperSetupError{
		LocalisableError: li18ngo.LocalisableError{Data: BedrockLoadViperSetupErrorTemplData{}},
		wrapped:          wrapped,
	}
}

// =============================================================================
// ❌ CreatingDecoderFor
//
// CreatingDecoderFor indicates that a mapstructure decoder could not be
// constructed for the named configuration section.
// =============================================================================

// CreatingDecoderForTemplData Error returned when a mapstructure decoder cannot
// be created for a config section.
type CreatingDecoderForTemplData struct {
	agenorTemplData
	// Key is the configuration section name
	Key string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td CreatingDecoderForTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "creating-decoder-for.dynamic-error",
		Description: "Error returned when a mapstructure decoder cannot be created for a config section",
		Other:       "Creating decoder for '{{.Key}}': '{{.Wrapped}}'",
	}
}

// CreatingDecoderForError Error returned when a mapstructure decoder cannot be
// created for a config section.
type CreatingDecoderForError struct {
	li18ngo.LocalisableError
	CreatingDecoderForTemplData
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e CreatingDecoderForError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e CreatingDecoderForError) Unwrap() error {
	return e.wrapped
}

// NewCreatingDecoderForError creates a new CreatingDecoderForError wrapping
// wrapped.
func NewCreatingDecoderForError(wrapped error, key string) error {
	td := CreatingDecoderForTemplData{
		agenorTemplData: agenorTemplData{},
		Key:             key,
		Wrapped:         wrapped.Error(),
	}
	return &CreatingDecoderForError{
		LocalisableError:            li18ngo.LocalisableError{Data: td},
		CreatingDecoderForTemplData: td,
		wrapped:                     wrapped,
	}
}

// =============================================================================
// ❌ DecodingSection
//
// DecodingSection indicates that mapstructure failed to decode the named
// configuration section into its target struct.
// =============================================================================

// DecodingSectionTemplData Error returned when mapstructure decoding of a
// config section fails.
type DecodingSectionTemplData struct {
	agenorTemplData
	// Key is the configuration section name
	Key string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td DecodingSectionTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "decoding-section.dynamic-error",
		Description: "Error returned when mapstructure decoding of a config section fails",
		Other:       "Decoding section '{{.Key}}': '{{.Wrapped}}'",
	}
}

// DecodingSectionError Error returned when mapstructure decoding of a config
// section fails.
type DecodingSectionError struct {
	li18ngo.LocalisableError
	DecodingSectionTemplData
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e DecodingSectionError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e DecodingSectionError) Unwrap() error {
	return e.wrapped
}

// NewDecodingSectionError creates a new DecodingSectionError wrapping wrapped.
func NewDecodingSectionError(wrapped error, key string) error {
	td := DecodingSectionTemplData{
		agenorTemplData: agenorTemplData{},
		Key:             key,
		Wrapped:         wrapped.Error(),
	}
	return &DecodingSectionError{
		LocalisableError:         li18ngo.LocalisableError{Data: td},
		DecodingSectionTemplData: td,
		wrapped:                  wrapped,
	}
}

// =============================================================================
// ❌ FlagsSectionUnexpectedType
//
// FlagsSectionUnexpectedType indicates that the flags section of the
// configuration file was decoded into an unexpected Go type.
// =============================================================================

// FlagsSectionUnexpectedTypeTemplData Error returned when the flags config
// section has an unexpected type.
type FlagsSectionUnexpectedTypeTemplData struct {
	agenorTemplData
	// TypeName is the unexpected type
	TypeName string
}

// Message creates a new i18n message using the template data.
func (td FlagsSectionUnexpectedTypeTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "flags-section-unexpected-type.dynamic-error",
		Description: "Error returned when the flags config section has an unexpected type",
		Other:       "Flags section has unexpected type '{{.TypeName}}'",
	}
}

// FlagsSectionUnexpectedTypeError Error returned when the flags config section
// has an unexpected type.
type FlagsSectionUnexpectedTypeError struct {
	li18ngo.LocalisableError
	FlagsSectionUnexpectedTypeTemplData
}

// NewFlagsSectionUnexpectedTypeError creates a new
// FlagsSectionUnexpectedTypeError.
func NewFlagsSectionUnexpectedTypeError(typeName string) error {
	td := FlagsSectionUnexpectedTypeTemplData{
		agenorTemplData: agenorTemplData{},
		TypeName:        typeName,
	}
	return &FlagsSectionUnexpectedTypeError{
		LocalisableError:                    li18ngo.LocalisableError{Data: td},
		FlagsSectionUnexpectedTypeTemplData: td,
	}
}

// =============================================================================
// ❌ PipelineNotFound
//
// PipelineNotFound indicates that a pipeline with the specified name was not
// found in the traversal configuration.
// =============================================================================

// PipelineNotFoundTemplData Pipeline not found in config error.
type PipelineNotFoundTemplData struct {
	agenorTemplData
	// Pipeline is the pipeline name that was not found
	Pipeline string
}

// Message creates a new i18n message using the template data.
func (td PipelineNotFoundTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "pipeline-not-found.dynamic-error",
		Description: "Pipeline not found in config error",
		Other:       "Pipeline not found: '{{.Pipeline}}'",
	}
}

// PipelineNotFoundError Pipeline not found in config error.
type PipelineNotFoundError struct {
	li18ngo.LocalisableError
	PipelineNotFoundTemplData
}

// NewPipelineNotFoundError creates a new PipelineNotFoundError.
func NewPipelineNotFoundError(pipeline string) error {
	td := PipelineNotFoundTemplData{
		agenorTemplData: agenorTemplData{},
		Pipeline:        pipeline,
	}
	return &PipelineNotFoundError{
		LocalisableError:          li18ngo.LocalisableError{Data: td},
		PipelineNotFoundTemplData: td,
	}
}

// =============================================================================
// ❌ UnsupportedFormat
//
// UnsupportedFormat indicates that the configuration format requested by the
// caller has not been registered with the format registry.
// =============================================================================

// UnsupportedFormatTemplData Error returned when an unregistered config format
// is requested.
type UnsupportedFormatTemplData struct {
	agenorTemplData
	// Format is the unsupported format
	Format string
}

// Message creates a new i18n message using the template data.
func (td UnsupportedFormatTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "unsupported-format.dynamic-error",
		Description: "Error returned when an unregistered config format is requested",
		Other:       "Unsupported format '{{.Format}}'",
	}
}

// UnsupportedFormatError Error returned when an unregistered config format is
// requested.
type UnsupportedFormatError struct {
	li18ngo.LocalisableError
	UnsupportedFormatTemplData
}

// NewUnsupportedFormatError creates a new UnsupportedFormatError.
func NewUnsupportedFormatError(format string) error {
	td := UnsupportedFormatTemplData{
		agenorTemplData: agenorTemplData{},
		Format:          format,
	}
	return &UnsupportedFormatError{
		LocalisableError:           li18ngo.LocalisableError{Data: td},
		UnsupportedFormatTemplData: td,
	}
}
