// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 📨 UsingConfigFile
//
// UsingConfigFile is printed on startup to indicate which configuration file
// has been loaded.
// =============================================================================

// UsingConfigFileTemplData Message to indicate which config is being used.
type UsingConfigFileTemplData struct {
	agenorTemplData
	// ConfigFileName is the name of the config file being used
	ConfigFileName string
}

// Message returns the i18n message for UsingConfigFileTemplData.
func (td UsingConfigFileTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "using-config-file",
		Description: "Message to indicate which config is being used",
		Other:       "Using config file: '{{.ConfigFileName}}'",
	}
}

// NewUsingConfigFileTemplData creates a new UsingConfigFileTemplData.
func NewUsingConfigFileTemplData(configFileName string) UsingConfigFileTemplData {
	return UsingConfigFileTemplData{
		agenorTemplData: agenorTemplData{},
		ConfigFileName:  configFileName,
	}
}
