// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"fmt"
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ CoreInvalidExtGlobFilterMissingSeparator
//
// CoreInvalidExtGlobFilterMissingSeparator is the sentinel core error for an
// invalid extended glob filter definition. Wrap this error using
// NewInvalidExtGlobFilterMissingSeparatorError.
// =============================================================================

// CoreInvalidExtGlobFilterMissingSeparatorErrorTemplData invalid glob ex filter
// definition; pattern is missing separator.
type CoreInvalidExtGlobFilterMissingSeparatorErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td CoreInvalidExtGlobFilterMissingSeparatorErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-extended-glob-filter-missing-separator.sentinel-error",
		Description: "invalid glob ex filter definition; pattern is missing separator",
		Other:       "Invalid glob ex filter definition; pattern is missing separator",
	}
}

// CoreInvalidExtGlobFilterMissingSeparatorError invalid glob ex filter
// definition; pattern is missing separator.
// Use errors.Is(err, locale.ErrCoreInvalidExtGlobFilterMissingSeparator) to
// test for this error.
type CoreInvalidExtGlobFilterMissingSeparatorError struct {
	li18ngo.LocalisableError
}

// ErrCoreInvalidExtGlobFilterMissingSeparator is the exported sentinel for
// CoreInvalidExtGlobFilterMissingSeparatorError.
var ErrCoreInvalidExtGlobFilterMissingSeparator = CoreInvalidExtGlobFilterMissingSeparatorError{
	LocalisableError: li18ngo.LocalisableError{
		Data: CoreInvalidExtGlobFilterMissingSeparatorErrorTemplData{},
	},
}

// =============================================================================
// ❌ CoreInvalidInCaseFilterDef
//
// CoreInvalidInCaseFilterDef is the sentinel core error for an invalid
// case-insensitive filter definition. Wrap this error using
// NewInvalidInCaseFilterDefError.
// =============================================================================

// CoreInvalidInCaseFilterDefErrorTemplData invalid incase filter definition;
// pattern is missing separator core error.
type CoreInvalidInCaseFilterDefErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td CoreInvalidInCaseFilterDefErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-incase-filter-definition.sentinel-error",
		Description: "invalid incase filter definition; pattern is missing separator core error",
		Other:       "Invalid incase filter definition; pattern is missing separator",
	}
}

// CoreInvalidInCaseFilterDefError invalid incase filter definition; pattern is
// missing separator core error.
// Use errors.Is(err, locale.ErrCoreInvalidInCaseFilterDef) to test for this
// error.
type CoreInvalidInCaseFilterDefError struct {
	li18ngo.LocalisableError
}

// ErrCoreInvalidInCaseFilterDef is the exported sentinel for
// CoreInvalidInCaseFilterDefError.
var ErrCoreInvalidInCaseFilterDef = CoreInvalidInCaseFilterDefError{
	LocalisableError: li18ngo.LocalisableError{
		Data: CoreInvalidInCaseFilterDefErrorTemplData{},
	},
}

// =============================================================================
// ❌ FilterChildGlobExNotSupported
//
// FilterChildGlobExNotSupported indicates that glob-ex filters cannot be
// applied to child nodes in this context.
// =============================================================================

// FilterChildGlobExNotSupportedErrorTemplData glob-ex filter not supported for
// children.
type FilterChildGlobExNotSupportedErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterChildGlobExNotSupportedErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "glob-ex-filter-not-supported-for-children.static-error",
		Description: "glob-ex filter not supported for children",
		Other:       "Glob-ex filter not supported for children",
	}
}

// FilterChildGlobExNotSupportedError glob-ex filter not supported for children.
type FilterChildGlobExNotSupportedError struct {
	li18ngo.LocalisableError
}

// ErrFilterChildGlobExNotSupported is the exported sentinel error for
// FilterChildGlobExNotSupportedError.
var ErrFilterChildGlobExNotSupported = FilterChildGlobExNotSupportedError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterChildGlobExNotSupportedErrorTemplData{},
	},
}

// =============================================================================
// ❌ FilterCustomNotSupported
//
// FilterCustomNotSupported indicates that custom filters cannot be applied to
// child nodes in this context.
// =============================================================================

// FilterCustomNotSupportedErrorTemplData custom filter not supported for
// children.
type FilterCustomNotSupportedErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterCustomNotSupportedErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "custom-filter-not-supported-for-children.static-error",
		Description: "custom filter not supported for children",
		Other:       "Custom filter not supported for children",
	}
}

// FilterCustomNotSupportedError custom filter not supported for children.
type FilterCustomNotSupportedError struct {
	li18ngo.LocalisableError
}

// ErrFilterCustomNotSupported is the exported sentinel error for
// FilterCustomNotSupportedError.
var ErrFilterCustomNotSupported = FilterCustomNotSupportedError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterCustomNotSupportedErrorTemplData{},
	},
}

// =============================================================================
// ❌ FilterIsNil
//
// FilterIsNil indicates that the caller passed a nil filter reference where a
// concrete filter implementation was required.
// =============================================================================

// FilterIsNilErrorTemplData filter is nil error.
type FilterIsNilErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterIsNilErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "filter-is-nil.static-error",
		Description: "filter is nil error",
		Other:       "Filter is nil",
	}
}

// FilterIsNilError filter is nil error.
type FilterIsNilError struct {
	li18ngo.LocalisableError
}

// ErrFilterIsNil is the exported sentinel error for FilterIsNilError.
var ErrFilterIsNil = FilterIsNilError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterIsNilErrorTemplData{},
	},
}

// =============================================================================
// ❌ FilterMissingType
//
// FilterMissingType indicates that the filter definition is missing a required
// type field.
// =============================================================================

// FilterMissingTypeErrorTemplData filter missing type.
type FilterMissingTypeErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterMissingTypeErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "filter-missing-type.static-error",
		Description: "filter missing type",
		Other:       "Filter missing type",
	}
}

// FilterMissingTypeError filter missing type.
type FilterMissingTypeError struct {
	li18ngo.LocalisableError
}

// ErrFilterMissingType is the exported sentinel error for
// FilterMissingTypeError.
var ErrFilterMissingType = FilterMissingTypeError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterMissingTypeErrorTemplData{},
	},
}

// =============================================================================
// ❌ FilterUndefined
//
// FilterUndefined indicates that the filter referenced in the traversal options
// has not been defined.
// =============================================================================

// FilterUndefinedErrorTemplData filter is undefined error.
type FilterUndefinedErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterUndefinedErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "filter-is-undefined.static-error",
		Description: "filter is undefined error",
		Other:       "Filter is undefined",
	}
}

// FilterUndefinedError filter is undefined error.
type FilterUndefinedError struct {
	li18ngo.LocalisableError
}

// ErrFilterUndefined is the exported sentinel error for FilterUndefinedError.
var ErrFilterUndefined = FilterUndefinedError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterUndefinedErrorTemplData{},
	},
}

// =============================================================================
// ❌ InvalidExtGlobFilterMissingSeparator
//
// InvalidExtGlobFilterMissingSeparator indicates that an extended glob filter
// definition is invalid because the pattern is missing the required separator
// character.
// =============================================================================

// InvalidExtGlobFilterMissingSeparatorTemplData invalid glob ex filter
// definition; pattern is missing separator.
type InvalidExtGlobFilterMissingSeparatorTemplData struct {
	agenorTemplData
	// Pattern is the invalid filter pattern
	Pattern string
}

// Message creates a new i18n message using the template data.
func (td InvalidExtGlobFilterMissingSeparatorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-glob-ex-filter-missing-separator.dynamic-error",
		Description: "invalid glob ex filter definition; pattern is missing separator",
		Other:       "Extended glob pattern missing separator, pattern: '{{.Pattern}}'",
	}
}

// InvalidExtGlobFilterMissingSeparatorError invalid glob ex filter definition;
// pattern is missing separator.
type InvalidExtGlobFilterMissingSeparatorError struct {
	li18ngo.LocalisableError
	InvalidExtGlobFilterMissingSeparatorTemplData
}

// NewInvalidExtGlobFilterMissingSeparatorError creates a new
// InvalidExtGlobFilterMissingSeparatorError.
func NewInvalidExtGlobFilterMissingSeparatorError(pattern string) error {
	td := InvalidExtGlobFilterMissingSeparatorTemplData{
		agenorTemplData: agenorTemplData{},
		Pattern:         pattern,
	}
	return &InvalidExtGlobFilterMissingSeparatorError{
		LocalisableError: li18ngo.LocalisableError{Data: td},
		InvalidExtGlobFilterMissingSeparatorTemplData: td,
	}
}

// =============================================================================
// ❌ InvalidExtendedGlobPattern
//
// InvalidExtendedGlobPattern indicates that the extended glob pattern is
// invalid.
// =============================================================================

// InvalidExtendedGlobPatternTemplData invalid extended glob pattern.
type InvalidExtendedGlobPatternTemplData struct {
	agenorTemplData
	// Pattern Is the invalid filter pattern
	Pattern string
}

// Message creates a new i18n message using the template data.
func (td InvalidExtendedGlobPatternTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-extended-glob-pattern.dynamic-error",
		Description: "invalid extended glob pattern",
		Other:       "Invalid extended glob pattern: '{{.Pattern}}'",
	}
}

// InvalidExtendedGlobPatternError invalid extended glob pattern.
type InvalidExtendedGlobPatternError struct {
	li18ngo.LocalisableError
	InvalidExtendedGlobPatternTemplData
}

// NewInvalidExtendedGlobPatternError creates a new
// InvalidExtendedGlobPatternError.
func NewInvalidExtendedGlobPatternError(pattern string) error {
	td := InvalidExtendedGlobPatternTemplData{
		agenorTemplData: agenorTemplData{},
		Pattern:         pattern,
	}
	return &InvalidExtendedGlobPatternError{
		LocalisableError:                    li18ngo.LocalisableError{Data: td},
		InvalidExtendedGlobPatternTemplData: td,
	}
}

// =============================================================================
// ❌ InvalidInCaseFilterDef
//
// InvalidInCaseFilterDef indicates that a case-insensitive filter definition is
// invalid because the pattern is missing the required separator.
// =============================================================================

// InvalidInCaseFilterDefTemplData invalid incase filter definition; pattern is
// missing separator wrapper error.
type InvalidInCaseFilterDefTemplData struct {
	agenorTemplData
	// Pattern is the invalid filter pattern
	Pattern string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td InvalidInCaseFilterDefTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-incase-filter-definition.dynamic-error",
		Description: "invalid incase filter definition; pattern is missing separator wrapper error",
		Other:       "'{{.Wrapped}}', pattern: '{{.Pattern}}'",
	}
}

// InvalidInCaseFilterDefError invalid incase filter definition; pattern is
// missing separator wrapper error.
type InvalidInCaseFilterDefError struct {
	li18ngo.LocalisableError
	InvalidInCaseFilterDefTemplData
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e InvalidInCaseFilterDefError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e InvalidInCaseFilterDefError) Unwrap() error {
	return e.wrapped
}

// NewInvalidInCaseFilterDefError creates a new InvalidInCaseFilterDefError
// wrapping wrapped.
func NewInvalidInCaseFilterDefError(wrapped error, pattern string) error {
	td := InvalidInCaseFilterDefTemplData{
		agenorTemplData: agenorTemplData{},
		Pattern:         pattern,
		Wrapped:         wrapped.Error(),
	}
	return &InvalidInCaseFilterDefError{
		LocalisableError:                li18ngo.LocalisableError{Data: td},
		InvalidInCaseFilterDefTemplData: td,
		wrapped:                         wrapped,
	}
}

// =============================================================================
// ❌ MissingCustomFilterDefinition
//
// MissingCustomFilterDefinition indicates that the traversal configuration
// references a custom filter but no definition for it was found.
// =============================================================================

// MissingCustomFilterDefinitionErrorTemplData config error
// missing-custom-filter-definition.
type MissingCustomFilterDefinitionErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td MissingCustomFilterDefinitionErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "missing-custom-filter-definition.static-error",
		Description: "config error missing-custom-filter-definition",
		Other:       "Missing custom filter definition (config error)",
	}
}

// MissingCustomFilterDefinitionError config error
// missing-custom-filter-definition.
type MissingCustomFilterDefinitionError struct {
	li18ngo.LocalisableError
}

// ErrMissingCustomFilterDefinition is the exported sentinel error for
// MissingCustomFilterDefinitionError.
var ErrMissingCustomFilterDefinition = MissingCustomFilterDefinitionError{
	LocalisableError: li18ngo.LocalisableError{
		Data: MissingCustomFilterDefinitionErrorTemplData{},
	},
}

// =============================================================================
// ❌ PolyFilterIsInvalid
//
// PolyFilterIsInvalid indicates that a poly filter definition fails validation.
// =============================================================================

// PolyFilterIsInvalidErrorTemplData poly filter definition is invalid error.
type PolyFilterIsInvalidErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td PolyFilterIsInvalidErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "poly-filter-is-invalid.static-error",
		Description: "poly filter definition is invalid error",
		Other:       "poly filter definition is invalid",
	}
}

// PolyFilterIsInvalidError poly filter definition is invalid error.
type PolyFilterIsInvalidError struct {
	li18ngo.LocalisableError
}

// ErrPolyFilterIsInvalid is the exported sentinel error for
// PolyFilterIsInvalidError.
var ErrPolyFilterIsInvalid = PolyFilterIsInvalidError{
	LocalisableError: li18ngo.LocalisableError{
		Data: PolyFilterIsInvalidErrorTemplData{},
	},
}
