// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ MutuallyExclusiveFlagsPresent
//
// This error is the equivalent of cobra's MarkFlagsMutuallyExclusive that does
// not work, if the flags are inherited. The cobra version only works when
// called from the command that actually defines the flags, so
// MarkInheritedFlagsMutuallyExclusive is a work-around for this deficiency.
// =============================================================================

// MutuallyExclusiveFlagsPresentTemplData Error message displayed when user
// specifies flags that can't be specified together.
type MutuallyExclusiveFlagsPresentTemplData struct {
	agenorTemplData
	// Command The command for which mutually exclusive flags have been defined
	Command string
	// Flags The set of mutually exclusive flags that have been defined
	Flags string
}

// Message creates a new i18n message using the template data.
func (td MutuallyExclusiveFlagsPresentTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "mutually-exclusive-flags-present.dynamic-error",
		Description: "Error message displayed when user specifies flags that can't be specified together",
		Other:       "Mutually exclusive flags '{{.Flags}}', defined for command '{{.Command}}'",
	}
}

// MutuallyExclusiveFlagsPresentError Error message displayed when user
// specifies flags that can't be specified together.
type MutuallyExclusiveFlagsPresentError struct {
	li18ngo.LocalisableError
	MutuallyExclusiveFlagsPresentTemplData
}

// NewMutuallyExclusiveFlagsPresentError creates a new
// MutuallyExclusiveFlagsPresentError.
func NewMutuallyExclusiveFlagsPresentError(command string, flags string) error {
	td := MutuallyExclusiveFlagsPresentTemplData{
		agenorTemplData: agenorTemplData{},
		Command:         command,
		Flags:           flags,
	}
	return &MutuallyExclusiveFlagsPresentError{
		LocalisableError:                       li18ngo.LocalisableError{Data: td},
		MutuallyExclusiveFlagsPresentTemplData: td,
	}
}
