// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ MarkInheritedFlagsOneRequired
//
// This error is the equivalent of cobra's MarkFlagsOneRequired that does not
// work, if the flag is inherited. The cobra version only works when called from
// the command that actually defines the flag, so MarkInheritedFlagsOneRequired
// is a work-around for this deficiency.
// =============================================================================

// MarkInheritedFlagsOneRequiredTemplData Error message displayed when user
// fails to specify one of a set of flags, required for a particular command.
type MarkInheritedFlagsOneRequiredTemplData struct {
	agenorTemplData
	// Command The command for which the flags are required
	Command string
	// Flags The set of flags, one of which is required
	Flags string
}

// Message creates a new i18n message using the template data.
func (td MarkInheritedFlagsOneRequiredTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "mark-inherited-flags-one-required.dynamic-error",
		Description: "Error message displayed when user fails to specify one of a set of flags, required for a particular command",
		Other:       "Missing flag for command '{{.Command}}', one of these must be specified: '{{.Flags}}'",
	}
}

// MarkInheritedFlagsOneRequiredError Error message displayed when user fails to
// specify one of a set of flags, required for a particular command.
type MarkInheritedFlagsOneRequiredError struct {
	li18ngo.LocalisableError
	MarkInheritedFlagsOneRequiredTemplData
}

// NewMarkInheritedFlagsOneRequiredError creates a new
// MarkInheritedFlagsOneRequiredError.
func NewMarkInheritedFlagsOneRequiredError(command string, flags string) error {
	td := MarkInheritedFlagsOneRequiredTemplData{
		agenorTemplData: agenorTemplData{},
		Command:         command,
		Flags:           flags,
	}
	return &MarkInheritedFlagsOneRequiredError{
		LocalisableError:                       li18ngo.LocalisableError{Data: td},
		MarkInheritedFlagsOneRequiredTemplData: td,
	}
}

// =============================================================================
// ❌ MarkInheritedFlagsRequired
//
// This error is the equivalent of cobra's MarkFlagsRequired that does not work,
// if the flag is inherited. The cobra version only works when called from the
// command that actually defines the flag, so MarkInheritedFlagsRequired is a
// work-around for this deficiency.
// =============================================================================

// MarkInheritedFlagsRequiredTemplData Error message displayed when user fails
// to specify a mandatory flag, required for a particular command.
type MarkInheritedFlagsRequiredTemplData struct {
	agenorTemplData
	// Command The command for which the flags are required
	Command string
	// Flag The name of the missing flag
	Flag string
}

// Message creates a new i18n message using the template data.
func (td MarkInheritedFlagsRequiredTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "mark-inherited-flag-required.dynamic-error",
		Description: "Error message displayed when user fails to specify a mandatory flag, required for a particular command",
		Other:       "missing mandatory flag: '{{.Flag}}' required for command '{{.Command}}'",
	}
}

// MarkInheritedFlagsRequiredError Error message displayed when user fails to
// specify a mandatory flag, required for a particular command.
type MarkInheritedFlagsRequiredError struct {
	li18ngo.LocalisableError
	MarkInheritedFlagsRequiredTemplData
}

// NewMarkInheritedFlagsRequiredError creates a new
// MarkInheritedFlagsRequiredError.
func NewMarkInheritedFlagsRequiredError(command string, flag string) error {
	td := MarkInheritedFlagsRequiredTemplData{
		agenorTemplData: agenorTemplData{},
		Command:         command,
		Flag:            flag,
	}
	return &MarkInheritedFlagsRequiredError{
		LocalisableError:                    li18ngo.LocalisableError{Data: td},
		MarkInheritedFlagsRequiredTemplData: td,
	}
}

// =============================================================================
// ❌ MutuallyExclusiveFlagsPresent
//
// This error is the equivalent of cobra's MarkFlagsMutuallyExclusive that does
// not work, if the flags are inherited. The cobra version only works when
// called from the command that actually defines the flags, so
// MarkInheritedFlagsMutuallyExclusive is a work-around for this deficiency.
// =============================================================================

// MutuallyExclusiveFlagsPresentTemplData Error message displayed when user
// specifies flags that can't be specified together.
type MutuallyExclusiveFlagsPresentTemplData struct {
	agenorTemplData
	// Command The command for which mutually exclusive flags have been defined
	Command string
	// Flags The set of mutually exclusive flags that have been defined
	Flags string
}

// Message creates a new i18n message using the template data.
func (td MutuallyExclusiveFlagsPresentTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "mutually-exclusive-flags-present.dynamic-error",
		Description: "Error message displayed when user specifies flags that can't be specified together",
		Other:       "Mutually exclusive flags '{{.Flags}}', defined for command '{{.Command}}'",
	}
}

// MutuallyExclusiveFlagsPresentError Error message displayed when user
// specifies flags that can't be specified together.
type MutuallyExclusiveFlagsPresentError struct {
	li18ngo.LocalisableError
	MutuallyExclusiveFlagsPresentTemplData
}

// NewMutuallyExclusiveFlagsPresentError creates a new
// MutuallyExclusiveFlagsPresentError.
func NewMutuallyExclusiveFlagsPresentError(command string, flags string) error {
	td := MutuallyExclusiveFlagsPresentTemplData{
		agenorTemplData: agenorTemplData{},
		Command:         command,
		Flags:           flags,
	}
	return &MutuallyExclusiveFlagsPresentError{
		LocalisableError:                       li18ngo.LocalisableError{Data: td},
		MutuallyExclusiveFlagsPresentTemplData: td,
	}
}
