// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 🧊 CommandIsAGhost
//
// CommandIsAGhost is use for the long and short text of a ghost command
// =============================================================================

// CommandIsAGhostTemplData command is a ghost.
type CommandIsAGhostTemplData struct {
	agenorTemplData
	// Command is the name of the ghost command
	Command string
}

// Message returns the i18n message for CommandIsAGhostTemplData.
func (td CommandIsAGhostTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "command-is-a-ghost",
		Description: "command is a ghost",
		Other:       "{{.Command}} is a ghost",
	}
}

// NewCommandIsAGhostTemplData creates a new CommandIsAGhostTemplData.
func NewCommandIsAGhostTemplData(command string) CommandIsAGhostTemplData {
	return CommandIsAGhostTemplData{
		agenorTemplData: agenorTemplData{},
		Command:         command,
	}
}
