// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 📨 ActionFailed
//
// ActionFailed is printed when a named action returns an error while processing
// a node.
// =============================================================================

// ActionFailedTemplData Printed when an action fails on a node during
// traversal.
type ActionFailedTemplData struct {
	agenorTemplData
	// Name is the name of the action that failed
	Name string
	// Path is the path of the node on which the action failed
	Path string
	// Err is the error message
	Err string
}

// Message returns the i18n message for ActionFailedTemplData.
func (td ActionFailedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "action-failed",
		Description: "Printed when an action fails on a node during traversal",
		Other:       "[!] Action '{{.Name}}' failed on '{{.Path}}': '{{.Err}}'",
	}
}

// NewActionFailedTemplData creates a new ActionFailedTemplData.
func NewActionFailedTemplData(name string, path string, err string) ActionFailedTemplData {
	return ActionFailedTemplData{
		agenorTemplData: agenorTemplData{},
		Name:            name,
		Path:            path,
		Err:             err,
	}
}

// =============================================================================
// 📨 ActionSkipped
//
// ActionSkipped is printed when an action is skipped
// =============================================================================

// ActionSkippedTemplData Printed when an action is skipped.
type ActionSkippedTemplData struct {
	agenorTemplData
	// Name Name of the action that was skipped
	Name string
	// Path Full path of the node that action that was skipped for
	Path string
}

// Message returns the i18n message for ActionSkippedTemplData.
func (td ActionSkippedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "action-skipped",
		Description: "Printed when an action is skipped",
		Other:       "[!] Action '{{.Name}}' skipped at '{{.Path}}'",
	}
}

// NewActionSkippedTemplData creates a new ActionSkippedTemplData.
func NewActionSkippedTemplData(name string, path string) ActionSkippedTemplData {
	return ActionSkippedTemplData{
		agenorTemplData: agenorTemplData{},
		Name:            name,
		Path:            path,
	}
}

// =============================================================================
// 📨 ActionVisited
//
// ActionVisited is printed for each node successfully processed by a named
// action.
// =============================================================================

// ActionVisitedTemplData Printed for each node successfully processed by an
// action.
type ActionVisitedTemplData struct {
	agenorTemplData
	// Name is the name of the action that succeeded
	Name string
	// Path is the path of the node successfully processed
	Path string
}

// Message returns the i18n message for ActionVisitedTemplData.
func (td ActionVisitedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "action-visited",
		Description: "Printed for each node successfully processed by an action",
		Other:       "[+] Actioned for '{{.Name}}' at '{{.Path}}'",
	}
}

// NewActionVisitedTemplData creates a new ActionVisitedTemplData.
func NewActionVisitedTemplData(name string, path string) ActionVisitedTemplData {
	return ActionVisitedTemplData{
		agenorTemplData: agenorTemplData{},
		Name:            name,
		Path:            path,
	}
}

// =============================================================================
// 📨 CommandIsNotUserInvocablePrompt
//
// CommandIsNotUserInvocablePrompt is the message shown during startup if the
// user accidentally invokes this ghost sub command, before exiting.
// =============================================================================

// CommandIsNotUserInvocablePromptTemplData command is not a user invocable.
type CommandIsNotUserInvocablePromptTemplData struct {
	agenorTemplData
	// Command is the name of the ghost command
	Command string
}

// Message returns the i18n message for
// CommandIsNotUserInvocablePromptTemplData.
func (td CommandIsNotUserInvocablePromptTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "command-is-not-user-invocable-prompt",
		Description: "command is not a user invocable",
		Other:       "{{.Command}} is hidden and not designed to be directly invoked",
	}
}

// NewCommandIsNotUserInvocablePromptTemplData creates a new
// CommandIsNotUserInvocablePromptTemplData.
func NewCommandIsNotUserInvocablePromptTemplData(command string) CommandIsNotUserInvocablePromptTemplData {
	return CommandIsNotUserInvocablePromptTemplData{
		agenorTemplData: agenorTemplData{},
		Command:         command,
	}
}

// =============================================================================
// 📨 NodeVisited
//
// NodeVisited is printed for each filesystem node encountered during traversal.
// =============================================================================

// NodeVisitedTemplData Printed for each node visited during traversal.
type NodeVisitedTemplData struct {
	agenorTemplData
	// Path is the path of the node being visited
	Path string
}

// Message returns the i18n message for NodeVisitedTemplData.
func (td NodeVisitedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "node-visited",
		Description: "Printed for each node visited during traversal",
		Other:       "Node Visited -> '{{.Path}}'",
	}
}

// NewNodeVisitedTemplData creates a new NodeVisitedTemplData.
func NewNodeVisitedTemplData(path string) NodeVisitedTemplData {
	return NodeVisitedTemplData{
		agenorTemplData: agenorTemplData{},
		Path:            path,
	}
}

// =============================================================================
// 📨 Permissive
//
// Word: permissive
// =============================================================================

// PermissiveTemplData Word: permissive.
type PermissiveTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for PermissiveTemplData.
func (td PermissiveTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "permissive.word",
		Description: "Word: permissive",
		Other:       "permissive",
	}
}

// =============================================================================
// 📨 PipelineFailed
//
// PipelineFailed is printed when a named pipeline returns an error while
// processing a node.
// =============================================================================

// PipelineFailedTemplData Printed when a pipeline fails on a node during
// traversal.
type PipelineFailedTemplData struct {
	agenorTemplData
	// Name is the name of the pipeline that failed
	Name string
	// Path is the path of the node on which the pipeline failed
	Path string
	// Err is the error message
	Err string
}

// Message returns the i18n message for PipelineFailedTemplData.
func (td PipelineFailedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "pipeline-failed",
		Description: "Printed when a pipeline fails on a node during traversal",
		Other:       "[!] Pipeline '{{.Name}}' failed on '{{.Path}}': '{{.Err}}'",
	}
}

// NewPipelineFailedTemplData creates a new PipelineFailedTemplData.
func NewPipelineFailedTemplData(name string, path string, err string) PipelineFailedTemplData {
	return PipelineFailedTemplData{
		agenorTemplData: agenorTemplData{},
		Name:            name,
		Path:            path,
		Err:             err,
	}
}

// =============================================================================
// 📨 PipelineVisited
//
// PipelineVisited is printed for each node successfully processed by a named
// pipeline.
// =============================================================================

// PipelineVisitedTemplData Printed for each node successfully processed by a
// pipeline.
type PipelineVisitedTemplData struct {
	agenorTemplData
	// Name is the name of the pipeline that succeeded
	Name string
	// Path is the path of the node successfully processed
	Path string
}

// Message returns the i18n message for PipelineVisitedTemplData.
func (td PipelineVisitedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "pipeline-visited",
		Description: "Printed for each node successfully processed by a pipeline",
		Other:       "[+] Pipeline succeeded for '{{.Name}}' at '{{.Path}}'",
	}
}

// NewPipelineVisitedTemplData creates a new PipelineVisitedTemplData.
func NewPipelineVisitedTemplData(name string, path string) PipelineVisitedTemplData {
	return PipelineVisitedTemplData{
		agenorTemplData: agenorTemplData{},
		Name:            name,
		Path:            path,
	}
}

// =============================================================================
// 📨 PlaceholderBreach
//
// Printed when a placeholder breach occurs during expansion.
// =============================================================================

// PlaceholderBreachTemplData Printed when placeholder breach occurs during
// expansion.
type PlaceholderBreachTemplData struct {
	agenorTemplData
	// Placeholder The placeholder that breached above the traversal root
	Placeholder string
	// ResolvedPath The resolved path of the placeholder that breached above the traversal root
	ResolvedPath string
}

// Message returns the i18n message for PlaceholderBreachTemplData.
func (td PlaceholderBreachTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "placeholder-breach",
		Description: "Printed when placeholder breach occurs during expansion",
		Other:       "[!] Placeholder: '{{.Placeholder}}' resolved to '{{.ResolvedPath}}'",
	}
}

// NewPlaceholderBreachTemplData creates a new PlaceholderBreachTemplData.
func NewPlaceholderBreachTemplData(placeholder string, resolvedPath string) PlaceholderBreachTemplData {
	return PlaceholderBreachTemplData{
		agenorTemplData: agenorTemplData{},
		Placeholder:     placeholder,
		ResolvedPath:    resolvedPath,
	}
}

// =============================================================================
// 📨 Prohibitive
//
// Word: prohibitive
// =============================================================================

// ProhibitiveTemplData Word: prohibitive.
type ProhibitiveTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for ProhibitiveTemplData.
func (td ProhibitiveTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "prohibitive.word",
		Description: "Word: prohibitive",
		Other:       "prohibitive",
	}
}

// =============================================================================
// 📨 TraversalComplete
//
// TraversalComplete is printed when a traversal finishes successfully,
// summarising the nodes visited and time elapsed.
// =============================================================================

// TraversalCompleteTemplData Printed on successful completion of a traversal.
type TraversalCompleteTemplData struct {
	agenorTemplData
	// Files is the total number of files visited
	Files uint
	// Dirs is the total number of directories visited
	Dirs uint
	// Elapsed is the total time elapsed during the traversal
	Elapsed string
}

// Message returns the i18n message for TraversalCompleteTemplData.
func (td TraversalCompleteTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "traversal-complete",
		Description: "Printed on successful completion of a traversal",
		Other:       "[+] Traversal complete successfully: {{.Files}} files, {{.Dirs}} dirs visited in {{.Elapsed}}",
	}
}

// NewTraversalCompleteTemplData creates a new TraversalCompleteTemplData.
func NewTraversalCompleteTemplData(files uint, dirs uint, elapsed string) TraversalCompleteTemplData {
	return TraversalCompleteTemplData{
		agenorTemplData: agenorTemplData{},
		Files:           files,
		Dirs:            dirs,
		Elapsed:         elapsed,
	}
}

// =============================================================================
// 📨 TraversalFailed
//
// TraversalFailed is printed when the traversal operation itself encounters a
// fatal error.
// =============================================================================

// TraversalFailedTemplData Printed when the traversal itself fails.
type TraversalFailedTemplData struct {
	agenorTemplData
	// Err Is the error message
	Err string
}

// Message returns the i18n message for TraversalFailedTemplData.
func (td TraversalFailedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "traversal-failed",
		Description: "Printed when the traversal itself fails",
		Other:       "[!] Traversal failed: '{{.Err}}'",
	}
}

// NewTraversalFailedTemplData creates a new TraversalFailedTemplData.
func NewTraversalFailedTemplData(err string) TraversalFailedTemplData {
	return TraversalFailedTemplData{
		agenorTemplData: agenorTemplData{},
		Err:             err,
	}
}
