// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"fmt"
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ CorePanicOccurred
//
// CorePanicOccurred is the sentinel core error indicating that a panic was
// intercepted during traversal.
// =============================================================================

// CorePanicOccurredErrorTemplData core error.
type CorePanicOccurredErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td CorePanicOccurredErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "panic-occurred.sentinel-error",
		Description: "core error",
		Other:       "Panic occurred",
	}
}

// CorePanicOccurredError core error.
// Use errors.Is(err, locale.ErrCorePanicOccurred) to test for this error.
type CorePanicOccurredError struct {
	li18ngo.LocalisableError
}

// ErrCorePanicOccurred is the exported sentinel for CorePanicOccurredError.
var ErrCorePanicOccurred = CorePanicOccurredError{
	LocalisableError: li18ngo.LocalisableError{
		Data: CorePanicOccurredErrorTemplData{},
	},
}

// =============================================================================
// ❌ CoreResumeFsMismatch
//
// CoreResumeFsMismatch is the sentinel core error for a filesystem mismatch
// detected during traversal or resume. Wrap using NewTraverseFsMismatchError or
// NewResumeFsMismatchError.
// =============================================================================

// CoreResumeFsMismatchErrorTemplData core resume file system mismatch error.
type CoreResumeFsMismatchErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td CoreResumeFsMismatchErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "resume-fs-mismatch.sentinel-error",
		Description: "core resume file system mismatch error",
		Other:       "Resume file system mismatch",
	}
}

// CoreResumeFsMismatchError core resume file system mismatch error.
// Use errors.Is(err, locale.ErrCoreResumeFsMismatch) to test for this error.
type CoreResumeFsMismatchError struct {
	li18ngo.LocalisableError
}

// ErrCoreResumeFsMismatch is the exported sentinel for
// CoreResumeFsMismatchError.
var ErrCoreResumeFsMismatch = CoreResumeFsMismatchError{
	LocalisableError: li18ngo.LocalisableError{
		Data: CoreResumeFsMismatchErrorTemplData{},
	},
}

// =============================================================================
// ❌ IDGeneratorFuncCantBeNil
//
// IDGeneratorFuncCantBeNil indicates that a nil function was supplied where an
// ID generator func is required.
// =============================================================================

// IDGeneratorFuncCantBeNilErrorTemplData id generator func is nil, should be
// defined.
type IDGeneratorFuncCantBeNilErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td IDGeneratorFuncCantBeNilErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "id-generator-func-cant-be-nil.static-error",
		Description: "id generator func is nil, should be defined",
		Other:       "ID generator func can't be nil",
	}
}

// IDGeneratorFuncCantBeNilError id generator func is nil, should be defined.
type IDGeneratorFuncCantBeNilError struct {
	li18ngo.LocalisableError
}

// ErrIDGeneratorFuncCantBeNil is the exported sentinel error for
// IDGeneratorFuncCantBeNilError.
var ErrIDGeneratorFuncCantBeNil = IDGeneratorFuncCantBeNilError{
	LocalisableError: li18ngo.LocalisableError{
		Data: IDGeneratorFuncCantBeNilErrorTemplData{},
	},
}

// =============================================================================
// ❌ InternalFailedToGetNavigatorDriver
//
// InternalFailedToGetNavigatorDriver indicates an internal failure when
// resolving the navigator driver. This is not expected during normal operation.
// =============================================================================

// InternalFailedToGetNavigatorDriverErrorTemplData failed to get navigator
// driver.
type InternalFailedToGetNavigatorDriverErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InternalFailedToGetNavigatorDriverErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "failed-to-get-navigator-driver.static-error",
		Description: "failed to get navigator driver",
		Other:       "Failed to get navigator driver",
	}
}

// InternalFailedToGetNavigatorDriverError failed to get navigator driver.
type InternalFailedToGetNavigatorDriverError struct {
	li18ngo.LocalisableError
}

// ErrInternalFailedToGetNavigatorDriver is the exported sentinel error for
// InternalFailedToGetNavigatorDriverError.
var ErrInternalFailedToGetNavigatorDriver = InternalFailedToGetNavigatorDriverError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InternalFailedToGetNavigatorDriverErrorTemplData{},
	},
}

// =============================================================================
// ❌ InvalidPath
//
// InvalidPath indicates that a path supplied by the caller fails validation.
// =============================================================================

// InvalidPathTemplData invalid path (dynamic error).
type InvalidPathTemplData struct {
	agenorTemplData
	// Path is the invalid path
	Path string
}

// Message creates a new i18n message using the template data.
func (td InvalidPathTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-path.dynamic-error",
		Description: "invalid path (dynamic error)",
		Other:       "Invalid Path: '{{.Path}}'",
	}
}

// InvalidPathError invalid path (dynamic error).
type InvalidPathError struct {
	li18ngo.LocalisableError
	InvalidPathTemplData
}

// NewInvalidPathError creates a new InvalidPathError.
func NewInvalidPathError(path string) error {
	td := InvalidPathTemplData{
		agenorTemplData: agenorTemplData{},
		Path:            path,
	}
	return &InvalidPathError{
		LocalisableError:     li18ngo.LocalisableError{Data: td},
		InvalidPathTemplData: td,
	}
}

// =============================================================================
// ❌ InvalidResumeStrategy
//
// InvalidResumeStrategy indicates that the resume strategy supplied by the
// caller is not one of the accepted values.
// =============================================================================

// InvalidResumeStrategyErrorTemplData invalid resume strategy type.
type InvalidResumeStrategyErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InvalidResumeStrategyErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-resume-strategy.static-error",
		Description: "invalid resume strategy type",
		Other:       "Invalid resume strategy, must be one of: [spawn, fast]",
	}
}

// InvalidResumeStrategyError invalid resume strategy type.
type InvalidResumeStrategyError struct {
	li18ngo.LocalisableError
}

// ErrInvalidResumeStrategy is the exported sentinel error for
// InvalidResumeStrategyError.
var ErrInvalidResumeStrategy = InvalidResumeStrategyError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InvalidResumeStrategyErrorTemplData{},
	},
}

// =============================================================================
// ❌ InvalidResumeValue
//
// InvalidResumeValue indicates that the resume value supplied by the caller is
// not in a valid value.
// =============================================================================

// InvalidResumeValueTemplData Invalid resume value format error.
type InvalidResumeValueTemplData struct {
	agenorTemplData
	// Actual The resume value provided
	Actual string
	// Values The valid values for resume, composed together, probably as CSV
	Values string
}

// Message creates a new i18n message using the template data.
func (td InvalidResumeValueTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-resume-value.dynamic-error",
		Description: "Invalid resume value format error",
		Other:       "Invalid resume value, actual: '{{.Actual}}', must be: {{.Values}}",
	}
}

// InvalidResumeValueError Invalid resume value format error.
type InvalidResumeValueError struct {
	li18ngo.LocalisableError
	InvalidResumeValueTemplData
}

// NewInvalidResumeValueError creates a new InvalidResumeValueError.
func NewInvalidResumeValueError(actual string, values string) error {
	td := InvalidResumeValueTemplData{
		agenorTemplData: agenorTemplData{},
		Actual:          actual,
		Values:          values,
	}
	return &InvalidResumeValueError{
		LocalisableError:            li18ngo.LocalisableError{Data: td},
		InvalidResumeValueTemplData: td,
	}
}

// =============================================================================
// ❌ InvalidSubscription
//
// InvalidSubscription indicates that the subscription type supplied by the
// caller is not one of the accepted values.
// =============================================================================

// InvalidSubscriptionErrorTemplData invalid subscription type.
type InvalidSubscriptionErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InvalidSubscriptionErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-subscription.static-error",
		Description: "invalid subscription type",
		Other:       "Invalid subscription type, must be one of: [files, dirs, all]",
	}
}

// InvalidSubscriptionError invalid subscription type.
type InvalidSubscriptionError struct {
	li18ngo.LocalisableError
}

// ErrInvalidSubscription is the exported sentinel error for
// InvalidSubscriptionError.
var ErrInvalidSubscription = InvalidSubscriptionError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InvalidSubscriptionErrorTemplData{},
	},
}

// =============================================================================
// ❌ PipelinePreflightFailure
//
// Error occurred during pipeline preflight checks
// =============================================================================

// PipelinePreflightFailureTemplData Error occurred during pipeline preflight
// checks.
type PipelinePreflightFailureTemplData struct {
	agenorTemplData
	// Pipeline The name of the pipeline for which the preflight check failed
	Pipeline string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td PipelinePreflightFailureTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "pipeline-preflight-failure.dynamic-error",
		Description: "Error occurred during pipeline preflight checks",
		Other:       "'{{.Wrapped}}' Preflight check failed for pipeline: '{{.Pipeline}}' ",
	}
}

// PipelinePreflightFailureError Error occurred during pipeline preflight
// checks.
type PipelinePreflightFailureError struct {
	li18ngo.LocalisableError
	PipelinePreflightFailureTemplData
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e PipelinePreflightFailureError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e PipelinePreflightFailureError) Unwrap() error {
	return e.wrapped
}

// NewPipelinePreflightFailureError creates a new PipelinePreflightFailureError
// wrapping wrapped.
func NewPipelinePreflightFailureError(wrapped error, pipeline string) error {
	td := PipelinePreflightFailureTemplData{
		agenorTemplData: agenorTemplData{},
		Pipeline:        pipeline,
		Wrapped:         wrapped.Error(),
	}
	return &PipelinePreflightFailureError{
		LocalisableError:                  li18ngo.LocalisableError{Data: td},
		PipelinePreflightFailureTemplData: td,
		wrapped:                           wrapped,
	}
}

// =============================================================================
// ❌ ResumeFsMismatch
//
// ResumeFsMismatch indicates that the filesystem passed to a resume operation
// does not match the filesystem recorded at the point the session was saved.
// =============================================================================

// ResumeFsMismatchErrorTemplData resume fs mismatch error.
type ResumeFsMismatchErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td ResumeFsMismatchErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "resume-fs-mismatch.static-error",
		Description: "resume fs mismatch error",
		Other:       "resume-fs file system mismatch",
	}
}

// ResumeFsMismatchError resume fs mismatch error.
type ResumeFsMismatchError struct {
	li18ngo.LocalisableError
}

// ErrResumeFsMismatch is the exported sentinel error for ResumeFsMismatchError.
var ErrResumeFsMismatch = ResumeFsMismatchError{
	LocalisableError: li18ngo.LocalisableError{
		Data: ResumeFsMismatchErrorTemplData{},
	},
}

// =============================================================================
// ❌ TraversalNotSaved
//
// Traversal state not saved as a result of a panic occurring during traversal
// =============================================================================

// TraversalNotSavedTemplData Error returned when a panic occurs during
// traversal and save of the traversal state fails.
type TraversalNotSavedTemplData struct {
	agenorTemplData
	// SavedTo The path the traversal state was attempted to be saved to
	SavedTo string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td TraversalNotSavedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "traversal-not-saved.dynamic-error",
		Description: "Error returned when a panic occurs during traversal and save of the traversal state fails",
		Other:       "'{{.Wrapped}}' Failed to save traversal state to: '{{.SavedTo}}' ",
	}
}

// TraversalNotSavedError Error returned when a panic occurs during traversal
// and save of the traversal state fails.
type TraversalNotSavedError struct {
	li18ngo.LocalisableError
	TraversalNotSavedTemplData
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e TraversalNotSavedError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e TraversalNotSavedError) Unwrap() error {
	return e.wrapped
}

// NewTraversalNotSavedError creates a new TraversalNotSavedError wrapping
// wrapped.
func NewTraversalNotSavedError(wrapped error, savedTo string) error {
	td := TraversalNotSavedTemplData{
		agenorTemplData: agenorTemplData{},
		SavedTo:         savedTo,
		Wrapped:         wrapped.Error(),
	}
	return &TraversalNotSavedError{
		LocalisableError:           li18ngo.LocalisableError{Data: td},
		TraversalNotSavedTemplData: td,
		wrapped:                    wrapped,
	}
}

// =============================================================================
// ❌ TraversalSaved
//
// Traversal state saved as a result of a panic occurring during traversal
// =============================================================================

// TraversalSavedTemplData Error returned when a panic occurs during traversal
// and save of the traversal state succeeds.
type TraversalSavedTemplData struct {
	agenorTemplData
	// SavedTo The path the traversal state was saved to
	SavedTo string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td TraversalSavedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "traversal-saved.dynamic-error",
		Description: "Error returned when a panic occurs during traversal and save of the traversal state succeeds",
		Other:       "'{{.Wrapped}}' Traversal state saved successfully to: '{{.SavedTo}}' ",
	}
}

// TraversalSavedError Error returned when a panic occurs during traversal and
// save of the traversal state succeeds.
type TraversalSavedError struct {
	li18ngo.LocalisableError
	TraversalSavedTemplData
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e TraversalSavedError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e TraversalSavedError) Unwrap() error {
	return e.wrapped
}

// NewTraversalSavedError creates a new TraversalSavedError wrapping wrapped.
func NewTraversalSavedError(wrapped error, savedTo string) error {
	td := TraversalSavedTemplData{
		agenorTemplData: agenorTemplData{},
		SavedTo:         savedTo,
		Wrapped:         wrapped.Error(),
	}
	return &TraversalSavedError{
		LocalisableError:        li18ngo.LocalisableError{Data: td},
		TraversalSavedTemplData: td,
		wrapped:                 wrapped,
	}
}

// =============================================================================
// ❌ TraverseFsMismatch
//
// TraverseFsMismatch indicates that the filesystem passed to the traversal does
// not match the filesystem recorded at the point the session was saved.
// =============================================================================

// TraverseFsMismatchErrorTemplData traverse fs mismatch error.
type TraverseFsMismatchErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td TraverseFsMismatchErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "traverse-fs-mismatch.static-error",
		Description: "traverse fs mismatch error",
		Other:       "traverse-fs file system mismatch",
	}
}

// TraverseFsMismatchError traverse fs mismatch error.
type TraverseFsMismatchError struct {
	li18ngo.LocalisableError
}

// ErrTraverseFsMismatch is the exported sentinel error for
// TraverseFsMismatchError.
var ErrTraverseFsMismatch = TraverseFsMismatchError{
	LocalisableError: li18ngo.LocalisableError{
		Data: TraverseFsMismatchErrorTemplData{},
	},
}

// =============================================================================
// ❌ UnEqualJSONConversion
//
// UnEqualJSONConversion indicates that a round-trip JSON conversion produced a
// result that does not equal the original value.
// =============================================================================

// UnEqualJSONConversionErrorTemplData JSON options conversion error.
type UnEqualJSONConversionErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UnEqualJSONConversionErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "un-equal-conversion.sentinel-error",
		Description: "JSON options conversion error",
		Other:       "Unequal JSON conversion",
	}
}

// UnEqualJSONConversionError JSON options conversion error.
// Use errors.Is(err, locale.ErrUnEqualJSONConversion) to test for this error.
type UnEqualJSONConversionError struct {
	li18ngo.LocalisableError
}

// ErrUnEqualJSONConversion is the exported sentinel for
// UnEqualJSONConversionError.
var ErrUnEqualJSONConversion = UnEqualJSONConversionError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UnEqualJSONConversionErrorTemplData{},
	},
}

// =============================================================================
// ❌ UsageMissingHandler
//
// UsageMissingHandler indicates that the command was invoked without
// registering a required handler.
// =============================================================================

// UsageMissingHandlerErrorTemplData usage missing handler.
type UsageMissingHandlerErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UsageMissingHandlerErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "usage-missing-handler.static-error",
		Description: "usage missing handler",
		Other:       "Usage missing handler",
	}
}

// UsageMissingHandlerError usage missing handler.
type UsageMissingHandlerError struct {
	li18ngo.LocalisableError
}

// ErrUsageMissingHandler is the exported sentinel error for
// UsageMissingHandlerError.
var ErrUsageMissingHandler = UsageMissingHandlerError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UsageMissingHandlerErrorTemplData{},
	},
}

// =============================================================================
// ❌ UsageMissingRestorePath
//
// UsageMissingRestorePath indicates that the command was invoked without the
// required restore path argument.
// =============================================================================

// UsageMissingRestorePathErrorTemplData usage missing restore path.
type UsageMissingRestorePathErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UsageMissingRestorePathErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "usage-missing-restore-path.static-error",
		Description: "usage missing restore path",
		Other:       "Usage missing restore path",
	}
}

// UsageMissingRestorePathError usage missing restore path.
type UsageMissingRestorePathError struct {
	li18ngo.LocalisableError
}

// ErrUsageMissingRestorePath is the exported sentinel error for
// UsageMissingRestorePathError.
var ErrUsageMissingRestorePath = UsageMissingRestorePathError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UsageMissingRestorePathErrorTemplData{},
	},
}

// =============================================================================
// ❌ UsageMissingSubscription
//
// UsageMissingSubscription indicates that the command was invoked without
// specifying a subscription type.
// =============================================================================

// UsageMissingSubscriptionErrorTemplData usage missing subscription.
type UsageMissingSubscriptionErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UsageMissingSubscriptionErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "usage-missing-subscription.static-error",
		Description: "usage missing subscription",
		Other:       "Usage missing subscription",
	}
}

// UsageMissingSubscriptionError usage missing subscription.
type UsageMissingSubscriptionError struct {
	li18ngo.LocalisableError
}

// ErrUsageMissingSubscription is the exported sentinel error for
// UsageMissingSubscriptionError.
var ErrUsageMissingSubscription = UsageMissingSubscriptionError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UsageMissingSubscriptionErrorTemplData{},
	},
}

// =============================================================================
// ❌ UsageMissingTreePath
//
// UsageMissingTreePath indicates that the command was invoked without the
// required tree path argument.
// =============================================================================

// UsageMissingTreePathErrorTemplData usage missing tree path.
type UsageMissingTreePathErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UsageMissingTreePathErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "usage-missing-tree-path.static-error",
		Description: "usage missing tree path",
		Other:       "Usage missing tree path",
	}
}

// UsageMissingTreePathError usage missing tree path.
type UsageMissingTreePathError struct {
	li18ngo.LocalisableError
}

// ErrUsageMissingTreePath is the exported sentinel error for
// UsageMissingTreePathError.
var ErrUsageMissingTreePath = UsageMissingTreePathError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UsageMissingTreePathErrorTemplData{},
	},
}

// =============================================================================
// ❌ WorkerPoolCreationFailed
//
// WorkerPoolCreationFailed indicates that the worker pool could not be
// initialised.
// =============================================================================

// WorkerPoolCreationFailedErrorTemplData failed to create worker pool.
type WorkerPoolCreationFailedErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td WorkerPoolCreationFailedErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "failed-to-create-worker-pool.static-error",
		Description: "failed to create worker pool",
		Other:       "Failed to create worker pool",
	}
}

// WorkerPoolCreationFailedError failed to create worker pool.
type WorkerPoolCreationFailedError struct {
	li18ngo.LocalisableError
}

// ErrWorkerPoolCreationFailed is the exported sentinel error for
// WorkerPoolCreationFailedError.
var ErrWorkerPoolCreationFailed = WorkerPoolCreationFailedError{
	LocalisableError: li18ngo.LocalisableError{
		Data: WorkerPoolCreationFailedErrorTemplData{},
	},
}
