// Code generated by i18n-gen. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"fmt"

	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ BedrockLoadDecoding
//
// BedrockLoadDecoding indicates that the configuration could not be decoded
// into the target struct during the bedrock.Load call.
// =============================================================================

// BedrockLoadDecodingErrorTemplData Error returned when config decoding fails
// during bedrock.Load.
type BedrockLoadDecodingErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td BedrockLoadDecodingErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "bedrock-load-decoding.jaywalk.static-error",
		Description: "Error returned when config decoding fails during bedrock.Load",
		Other:       "bedrock.Load: decoding",
	}
}

// BedrockLoadDecodingError Error returned when config decoding fails during
// bedrock.Load.
type BedrockLoadDecodingError struct {
	li18ngo.LocalisableError
	Wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e BedrockLoadDecodingError) Error() string {
	return fmt.Sprintf("%v, %v", e.Wrapped.Error(), li18ngo.Text(e.Data))
}

// Unwrap returns the wrapped error.
func (e BedrockLoadDecodingError) Unwrap() error {
	return e.Wrapped
}

// NewBedrockLoadDecodingError creates a new BedrockLoadDecodingError wrapping
// wrapped.
func NewBedrockLoadDecodingError(wrapped error) error {
	return &BedrockLoadDecodingError{
		LocalisableError: li18ngo.LocalisableError{Data: BedrockLoadDecodingErrorTemplData{}},
		Wrapped:          wrapped,
	}
}

// =============================================================================
// ❌ BedrockLoadReadingConfig
//
// BedrockLoadReadingConfig indicates that the configuration file could not be
// read during the bedrock.Load call.
// =============================================================================

// BedrockLoadReadingConfigErrorTemplData Error returned when reading the config
// file fails during bedrock.Load.
type BedrockLoadReadingConfigErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td BedrockLoadReadingConfigErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "bedrock-load-reading-config.jaywalk.static-error",
		Description: "Error returned when reading the config file fails during bedrock.Load",
		Other:       "bedrock.Load: reading config",
	}
}

// BedrockLoadReadingConfigError Error returned when reading the config file
// fails during bedrock.Load.
type BedrockLoadReadingConfigError struct {
	li18ngo.LocalisableError
	Wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e BedrockLoadReadingConfigError) Error() string {
	return fmt.Sprintf("%v, %v", e.Wrapped.Error(), li18ngo.Text(e.Data))
}

// Unwrap returns the wrapped error.
func (e BedrockLoadReadingConfigError) Unwrap() error {
	return e.Wrapped
}

// NewBedrockLoadReadingConfigError creates a new BedrockLoadReadingConfigError
// wrapping wrapped.
func NewBedrockLoadReadingConfigError(wrapped error) error {
	return &BedrockLoadReadingConfigError{
		LocalisableError: li18ngo.LocalisableError{Data: BedrockLoadReadingConfigErrorTemplData{}},
		Wrapped:          wrapped,
	}
}

// =============================================================================
// ❌ BedrockLoadValidation
//
// BedrockLoadValidation indicates that the decoded configuration failed
// validation during the bedrock.Load call.
// =============================================================================

// BedrockLoadValidationErrorTemplData Error returned when config validation
// fails during bedrock.Load.
type BedrockLoadValidationErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td BedrockLoadValidationErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "bedrock-load-validation.jaywalk.static-error",
		Description: "Error returned when config validation fails during bedrock.Load",
		Other:       "bedrock.Load: validation",
	}
}

// BedrockLoadValidationError Error returned when config validation fails during
// bedrock.Load.
type BedrockLoadValidationError struct {
	li18ngo.LocalisableError
	Wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e BedrockLoadValidationError) Error() string {
	return fmt.Sprintf("%v, %v", e.Wrapped.Error(), li18ngo.Text(e.Data))
}

// Unwrap returns the wrapped error.
func (e BedrockLoadValidationError) Unwrap() error {
	return e.Wrapped
}

// NewBedrockLoadValidationError creates a new BedrockLoadValidationError
// wrapping wrapped.
func NewBedrockLoadValidationError(wrapped error) error {
	return &BedrockLoadValidationError{
		LocalisableError: li18ngo.LocalisableError{Data: BedrockLoadValidationErrorTemplData{}},
		Wrapped:          wrapped,
	}
}

// =============================================================================
// ❌ BedrockLoadViperSetup
//
// BedrockLoadViperSetup indicates that viper could not be configured during the
// bedrock.Load call.
// =============================================================================

// BedrockLoadViperSetupErrorTemplData Error returned when viper setup fails
// during bedrock.Load.
type BedrockLoadViperSetupErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td BedrockLoadViperSetupErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "bedrock-load-viper-setup.jaywalk.static-error",
		Description: "Error returned when viper setup fails during bedrock.Load",
		Other:       "bedrock.Load: viper setup",
	}
}

// BedrockLoadViperSetupError Error returned when viper setup fails during
// bedrock.Load.
type BedrockLoadViperSetupError struct {
	li18ngo.LocalisableError
	Wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e BedrockLoadViperSetupError) Error() string {
	return fmt.Sprintf("%v, %v", e.Wrapped.Error(), li18ngo.Text(e.Data))
}

// Unwrap returns the wrapped error.
func (e BedrockLoadViperSetupError) Unwrap() error {
	return e.Wrapped
}

// NewBedrockLoadViperSetupError creates a new BedrockLoadViperSetupError
// wrapping wrapped.
func NewBedrockLoadViperSetupError(wrapped error) error {
	return &BedrockLoadViperSetupError{
		LocalisableError: li18ngo.LocalisableError{Data: BedrockLoadViperSetupErrorTemplData{}},
		Wrapped:          wrapped,
	}
}

// =============================================================================
// ❌ CoreInvalidExtGlobFilterMissingSeparator
//
// CoreInvalidExtGlobFilterMissingSeparator is the sentinel core error for an
// invalid extended glob filter definition. Wrap this error using
// NewInvalidExtGlobFilterMissingSeparatorError.
// =============================================================================

// CoreInvalidExtGlobFilterMissingSeparatorErrorTemplData invalid glob ex filter
// definition; pattern is missing separator.
type CoreInvalidExtGlobFilterMissingSeparatorErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td CoreInvalidExtGlobFilterMissingSeparatorErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-extended-glob-filter-missing-separator.sentinel-error",
		Description: "invalid glob ex filter definition; pattern is missing separator",
		Other:       "invalid glob ex filter definition; pattern is missing separator",
	}
}

// CoreInvalidExtGlobFilterMissingSeparatorError invalid glob ex filter
// definition; pattern is missing separator.
// Use errors.Is(err, locale.ErrCoreInvalidExtGlobFilterMissingSeparator) to
// test for this error.
type CoreInvalidExtGlobFilterMissingSeparatorError struct {
	li18ngo.LocalisableError
}

// ErrCoreInvalidExtGlobFilterMissingSeparator is the exported sentinel for
// CoreInvalidExtGlobFilterMissingSeparatorError.
var ErrCoreInvalidExtGlobFilterMissingSeparator = CoreInvalidExtGlobFilterMissingSeparatorError{
	LocalisableError: li18ngo.LocalisableError{
		Data: CoreInvalidExtGlobFilterMissingSeparatorErrorTemplData{},
	},
}

// =============================================================================
// ❌ CoreInvalidInCaseFilterDef
//
// CoreInvalidInCaseFilterDef is the sentinel core error for an invalid
// case-insensitive filter definition. Wrap this error using
// NewInvalidInCaseFilterDefError.
// =============================================================================

// CoreInvalidInCaseFilterDefErrorTemplData invalid incase filter definition;
// pattern is missing separator core error.
type CoreInvalidInCaseFilterDefErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td CoreInvalidInCaseFilterDefErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-incase-filter-definition.sentinel-error",
		Description: "invalid incase filter definition; pattern is missing separator core error",
		Other:       "invalid incase filter definition; pattern is missing separator",
	}
}

// CoreInvalidInCaseFilterDefError invalid incase filter definition; pattern is
// missing separator core error.
// Use errors.Is(err, locale.ErrCoreInvalidInCaseFilterDef) to test for this
// error.
type CoreInvalidInCaseFilterDefError struct {
	li18ngo.LocalisableError
}

// ErrCoreInvalidInCaseFilterDef is the exported sentinel for
// CoreInvalidInCaseFilterDefError.
var ErrCoreInvalidInCaseFilterDef = CoreInvalidInCaseFilterDefError{
	LocalisableError: li18ngo.LocalisableError{
		Data: CoreInvalidInCaseFilterDefErrorTemplData{},
	},
}

// =============================================================================
// ❌ CorePanicOccurred
//
// CorePanicOccurred is the sentinel core error indicating that a panic was
// intercepted during traversal.
// =============================================================================

// CorePanicOccurredErrorTemplData core error.
type CorePanicOccurredErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td CorePanicOccurredErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "panic-occurred.sentinel-error",
		Description: "core error",
		Other:       "panic occurred",
	}
}

// CorePanicOccurredError core error.
// Use errors.Is(err, locale.ErrCorePanicOccurred) to test for this error.
type CorePanicOccurredError struct {
	li18ngo.LocalisableError
}

// ErrCorePanicOccurred is the exported sentinel for CorePanicOccurredError.
var ErrCorePanicOccurred = CorePanicOccurredError{
	LocalisableError: li18ngo.LocalisableError{
		Data: CorePanicOccurredErrorTemplData{},
	},
}

// =============================================================================
// ❌ CoreResumeFsMismatch
//
// CoreResumeFsMismatch is the sentinel core error for a filesystem mismatch
// detected during traversal or resume. Wrap using NewTraverseFsMismatchError or
// NewResumeFsMismatchError.
// =============================================================================

// CoreResumeFsMismatchErrorTemplData core resume file system mismatch error.
type CoreResumeFsMismatchErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td CoreResumeFsMismatchErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "resume-fs-mismatch.sentinel-error",
		Description: "core resume file system mismatch error",
		Other:       "resume file system mismatch",
	}
}

// CoreResumeFsMismatchError core resume file system mismatch error.
// Use errors.Is(err, locale.ErrCoreResumeFsMismatch) to test for this error.
type CoreResumeFsMismatchError struct {
	li18ngo.LocalisableError
}

// ErrCoreResumeFsMismatch is the exported sentinel for
// CoreResumeFsMismatchError.
var ErrCoreResumeFsMismatch = CoreResumeFsMismatchError{
	LocalisableError: li18ngo.LocalisableError{
		Data: CoreResumeFsMismatchErrorTemplData{},
	},
}

// =============================================================================
// ❌ CreatingDecoderFor
//
// CreatingDecoderFor indicates that a mapstructure decoder could not be
// constructed for the named configuration section.
// =============================================================================

// CreatingDecoderForTemplData Error returned when a mapstructure decoder cannot
// be created for a config section.
type CreatingDecoderForTemplData struct {
	agenorTemplData
	// Key is the configuration section name
	Key string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td CreatingDecoderForTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "creating-decoder-for.jaywalk.dynamic-error",
		Description: "Error returned when a mapstructure decoder cannot be created for a config section",
		Other:       "creating decoder for '{{.Key}}': '{{.Wrapped}}'",
	}
}

// CreatingDecoderForError Error returned when a mapstructure decoder cannot be
// created for a config section.
type CreatingDecoderForError struct {
	li18ngo.LocalisableError
	Wrapped error
	Key     string
}

// Error returns the combined wrapped and localised error message.
func (e CreatingDecoderForError) Error() string {
	return fmt.Sprintf("%v, %v", e.Wrapped.Error(), li18ngo.Text(e.Data))
}

// Unwrap returns the wrapped error.
func (e CreatingDecoderForError) Unwrap() error {
	return e.Wrapped
}

// NewCreatingDecoderForError creates a new CreatingDecoderForError wrapping
// wrapped.
func NewCreatingDecoderForError(wrapped error, key string) error {
	return &CreatingDecoderForError{
		LocalisableError: li18ngo.LocalisableError{
			Data: CreatingDecoderForTemplData{
				Key:     key,
				Wrapped: wrapped.Error(),
			},
		},
		Wrapped: wrapped,
		Key:     key,
	}
}

// =============================================================================
// ❌ DecodingSection
//
// DecodingSection indicates that mapstructure failed to decode the named
// configuration section into its target struct.
// =============================================================================

// DecodingSectionTemplData Error returned when mapstructure decoding of a
// config section fails.
type DecodingSectionTemplData struct {
	agenorTemplData
	// Key is the configuration section name
	Key string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td DecodingSectionTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "decoding-section.jaywalk.dynamic-error",
		Description: "Error returned when mapstructure decoding of a config section fails",
		Other:       "decoding section '{{.Key}}': '{{.Wrapped}}'",
	}
}

// DecodingSectionError Error returned when mapstructure decoding of a config
// section fails.
type DecodingSectionError struct {
	li18ngo.LocalisableError
	Wrapped error
	Key     string
}

// Error returns the combined wrapped and localised error message.
func (e DecodingSectionError) Error() string {
	return fmt.Sprintf("%v, %v", e.Wrapped.Error(), li18ngo.Text(e.Data))
}

// Unwrap returns the wrapped error.
func (e DecodingSectionError) Unwrap() error {
	return e.Wrapped
}

// NewDecodingSectionError creates a new DecodingSectionError wrapping wrapped.
func NewDecodingSectionError(wrapped error, key string) error {
	return &DecodingSectionError{
		LocalisableError: li18ngo.LocalisableError{
			Data: DecodingSectionTemplData{
				Key:     key,
				Wrapped: wrapped.Error(),
			},
		},
		Wrapped: wrapped,
		Key:     key,
	}
}

// =============================================================================
// ❌ FilterChildGlobExNotSupported
//
// FilterChildGlobExNotSupported indicates that glob-ex filters cannot be
// applied to child nodes in this context.
// =============================================================================

// FilterChildGlobExNotSupportedErrorTemplData glob-ex filter not supported for
// children.
type FilterChildGlobExNotSupportedErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterChildGlobExNotSupportedErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "glob-ex-filter-not-supported-for-children.static-error.static-error",
		Description: "glob-ex filter not supported for children",
		Other:       "glob-ex filter not supported for children",
	}
}

// FilterChildGlobExNotSupportedError glob-ex filter not supported for children.
type FilterChildGlobExNotSupportedError struct {
	li18ngo.LocalisableError
}

// ErrFilterChildGlobExNotSupported is the exported sentinel error for
// FilterChildGlobExNotSupportedError.
var ErrFilterChildGlobExNotSupported = FilterChildGlobExNotSupportedError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterChildGlobExNotSupportedErrorTemplData{},
	},
}

// =============================================================================
// ❌ FilterCustomNotSupported
//
// FilterCustomNotSupported indicates that custom filters cannot be applied to
// child nodes in this context.
// =============================================================================

// FilterCustomNotSupportedErrorTemplData custom filter not supported for
// children.
type FilterCustomNotSupportedErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterCustomNotSupportedErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "custom-filter-not-supported-for-children.static-error.static-error",
		Description: "custom filter not supported for children",
		Other:       "custom filter not supported for children",
	}
}

// FilterCustomNotSupportedError custom filter not supported for children.
type FilterCustomNotSupportedError struct {
	li18ngo.LocalisableError
}

// ErrFilterCustomNotSupported is the exported sentinel error for
// FilterCustomNotSupportedError.
var ErrFilterCustomNotSupported = FilterCustomNotSupportedError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterCustomNotSupportedErrorTemplData{},
	},
}

// =============================================================================
// ❌ FilterIsNil
//
// FilterIsNil indicates that the caller passed a nil filter reference where a
// concrete filter implementation was required.
// =============================================================================

// FilterIsNilErrorTemplData filter is nil error.
type FilterIsNilErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterIsNilErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "filter-is-nil.static-error",
		Description: "filter is nil error",
		Other:       "filter is nil",
	}
}

// FilterIsNilError filter is nil error.
type FilterIsNilError struct {
	li18ngo.LocalisableError
}

// ErrFilterIsNil is the exported sentinel error for FilterIsNilError.
var ErrFilterIsNil = FilterIsNilError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterIsNilErrorTemplData{},
	},
}

// =============================================================================
// ❌ FilterMissingType
//
// FilterMissingType indicates that the filter definition is missing a required
// type field.
// =============================================================================

// FilterMissingTypeErrorTemplData filter missing type.
type FilterMissingTypeErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterMissingTypeErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "filter-missing-type.static-error",
		Description: "filter missing type",
		Other:       "filter missing type",
	}
}

// FilterMissingTypeError filter missing type.
type FilterMissingTypeError struct {
	li18ngo.LocalisableError
}

// ErrFilterMissingType is the exported sentinel error for
// FilterMissingTypeError.
var ErrFilterMissingType = FilterMissingTypeError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterMissingTypeErrorTemplData{},
	},
}

// =============================================================================
// ❌ FilterUndefined
//
// FilterUndefined indicates that the filter referenced in the traversal options
// has not been defined.
// =============================================================================

// FilterUndefinedErrorTemplData filter is undefined error.
type FilterUndefinedErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td FilterUndefinedErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "filter-is-undefined.static-error",
		Description: "filter is undefined error",
		Other:       "filter is undefined",
	}
}

// FilterUndefinedError filter is undefined error.
type FilterUndefinedError struct {
	li18ngo.LocalisableError
}

// ErrFilterUndefined is the exported sentinel error for FilterUndefinedError.
var ErrFilterUndefined = FilterUndefinedError{
	LocalisableError: li18ngo.LocalisableError{
		Data: FilterUndefinedErrorTemplData{},
	},
}

// =============================================================================
// ❌ FlagsSectionUnexpectedType
//
// FlagsSectionUnexpectedType indicates that the flags section of the
// configuration file was decoded into an unexpected Go type.
// =============================================================================

// FlagsSectionUnexpectedTypeTemplData Error returned when the flags config
// section has an unexpected type.
type FlagsSectionUnexpectedTypeTemplData struct {
	agenorTemplData
	// TypeName is the unexpected type
	TypeName string
}

// Message creates a new i18n message using the template data.
func (td FlagsSectionUnexpectedTypeTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "flags-section-unexpected-type.jaywalk.dynamic-error",
		Description: "Error returned when the flags config section has an unexpected type",
		Other:       "flags section has unexpected type '{{.TypeName}}'",
	}
}

// FlagsSectionUnexpectedTypeError Error returned when the flags config section
// has an unexpected type.
type FlagsSectionUnexpectedTypeError struct {
	li18ngo.LocalisableError
	TypeName string
}

// NewFlagsSectionUnexpectedTypeError creates a new
// FlagsSectionUnexpectedTypeError.
func NewFlagsSectionUnexpectedTypeError(typeName string) error {
	return &FlagsSectionUnexpectedTypeError{
		LocalisableError: li18ngo.LocalisableError{
			Data: FlagsSectionUnexpectedTypeTemplData{
				TypeName: typeName,
			},
		},
		TypeName: typeName,
	}
}

// =============================================================================
// ❌ IDGeneratorFuncCantBeNil
//
// IDGeneratorFuncCantBeNil indicates that a nil function was supplied where an
// ID generator func is required.
// =============================================================================

// IDGeneratorFuncCantBeNilErrorTemplData id generator func is nil, should be
// defined.
type IDGeneratorFuncCantBeNilErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td IDGeneratorFuncCantBeNilErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "id-generator-func-cant-be-nil.static-error",
		Description: "id generator func is nil, should be defined",
		Other:       "id generator func can't be nil",
	}
}

// IDGeneratorFuncCantBeNilError id generator func is nil, should be defined.
type IDGeneratorFuncCantBeNilError struct {
	li18ngo.LocalisableError
}

// ErrIDGeneratorFuncCantBeNil is the exported sentinel error for
// IDGeneratorFuncCantBeNilError.
var ErrIDGeneratorFuncCantBeNil = IDGeneratorFuncCantBeNilError{
	LocalisableError: li18ngo.LocalisableError{
		Data: IDGeneratorFuncCantBeNilErrorTemplData{},
	},
}

// =============================================================================
// ❌ InternalFailedToGetNavigatorDriver
//
// InternalFailedToGetNavigatorDriver indicates an internal failure when
// resolving the navigator driver. This is not expected during normal operation.
// =============================================================================

// InternalFailedToGetNavigatorDriverErrorTemplData failed to get navigator
// driver.
type InternalFailedToGetNavigatorDriverErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InternalFailedToGetNavigatorDriverErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "failed-to-get-navigator-driver.static-error",
		Description: "failed to get navigator driver",
		Other:       "failed to get navigator driver",
	}
}

// InternalFailedToGetNavigatorDriverError failed to get navigator driver.
type InternalFailedToGetNavigatorDriverError struct {
	li18ngo.LocalisableError
}

// ErrInternalFailedToGetNavigatorDriver is the exported sentinel error for
// InternalFailedToGetNavigatorDriverError.
var ErrInternalFailedToGetNavigatorDriver = InternalFailedToGetNavigatorDriverError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InternalFailedToGetNavigatorDriverErrorTemplData{},
	},
}

// =============================================================================
// ❌ InvalidExtGlobFilterMissingSeparator
//
// InvalidExtGlobFilterMissingSeparator indicates that an extended glob filter
// definition is invalid because the pattern is missing the required separator
// character.
// =============================================================================

// InvalidExtGlobFilterMissingSeparatorTemplData invalid glob ex filter
// definition; pattern is missing separator.
type InvalidExtGlobFilterMissingSeparatorTemplData struct {
	agenorTemplData
	// Pattern is the invalid filter pattern
	Pattern string
}

// Message creates a new i18n message using the template data.
func (td InvalidExtGlobFilterMissingSeparatorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-glob-ex-filter-missing-separator.dynamic-error",
		Description: "invalid glob ex filter definition; pattern is missing separator",
		Other:       "extended glob pattern missing separator, pattern: '{{.Pattern}}'",
	}
}

// InvalidExtGlobFilterMissingSeparatorError invalid glob ex filter definition;
// pattern is missing separator.
type InvalidExtGlobFilterMissingSeparatorError struct {
	li18ngo.LocalisableError
	Pattern string
}

// NewInvalidExtGlobFilterMissingSeparatorError creates a new
// InvalidExtGlobFilterMissingSeparatorError.
func NewInvalidExtGlobFilterMissingSeparatorError(pattern string) error {
	return &InvalidExtGlobFilterMissingSeparatorError{
		LocalisableError: li18ngo.LocalisableError{
			Data: InvalidExtGlobFilterMissingSeparatorTemplData{
				Pattern: pattern,
			},
		},
		Pattern: pattern,
	}
}

// =============================================================================
// ❌ InvalidFileSamplingSpecMissingFiles
//
// InvalidFileSamplingSpecMissingFiles indicates that the file sampling
// specification is invalid because the required number-of-files field is
// absent.
// =============================================================================

// InvalidFileSamplingSpecMissingFilesErrorTemplData invalid file sampling
// specification, missing no of files.
type InvalidFileSamplingSpecMissingFilesErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InvalidFileSamplingSpecMissingFilesErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-file-sampling-spec-missing-files.static-error",
		Description: "invalid file sampling specification, missing no of files",
		Other:       "invalid file sampling specification, missing no of files",
	}
}

// InvalidFileSamplingSpecMissingFilesError invalid file sampling specification,
// missing no of files.
type InvalidFileSamplingSpecMissingFilesError struct {
	li18ngo.LocalisableError
}

// ErrInvalidFileSamplingSpecMissingFiles is the exported sentinel error for
// InvalidFileSamplingSpecMissingFilesError.
var ErrInvalidFileSamplingSpecMissingFiles = InvalidFileSamplingSpecMissingFilesError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InvalidFileSamplingSpecMissingFilesErrorTemplData{},
	},
}

// =============================================================================
// ❌ InvalidInCaseFilterDef
//
// InvalidInCaseFilterDef indicates that a case-insensitive filter definition is
// invalid because the pattern is missing the required separator.
// =============================================================================

// InvalidInCaseFilterDefTemplData invalid incase filter definition; pattern is
// missing separator wrapper error.
type InvalidInCaseFilterDefTemplData struct {
	agenorTemplData
	// Pattern is the invalid filter pattern
	Pattern string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td InvalidInCaseFilterDefTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-incase-filter-definition.dynamic-error",
		Description: "invalid incase filter definition; pattern is missing separator wrapper error",
		Other:       "'{{.Wrapped}}', pattern: '{{.Pattern}}'",
	}
}

// InvalidInCaseFilterDefError invalid incase filter definition; pattern is
// missing separator wrapper error.
type InvalidInCaseFilterDefError struct {
	li18ngo.LocalisableError
	Wrapped error
	Pattern string
}

// Error returns the combined wrapped and localised error message.
func (e InvalidInCaseFilterDefError) Error() string {
	return fmt.Sprintf("%v, %v", e.Wrapped.Error(), li18ngo.Text(e.Data))
}

// Unwrap returns the wrapped error.
func (e InvalidInCaseFilterDefError) Unwrap() error {
	return e.Wrapped
}

// NewInvalidInCaseFilterDefError creates a new InvalidInCaseFilterDefError
// wrapping wrapped.
func NewInvalidInCaseFilterDefError(wrapped error, pattern string) error {
	return &InvalidInCaseFilterDefError{
		LocalisableError: li18ngo.LocalisableError{
			Data: InvalidInCaseFilterDefTemplData{
				Pattern: pattern,
				Wrapped: wrapped.Error(),
			},
		},
		Wrapped: wrapped,
		Pattern: pattern,
	}
}

// =============================================================================
// ❌ InvalidPath
//
// InvalidPath indicates that a path supplied by the caller fails validation.
// =============================================================================

// InvalidPathTemplData invalid path (dynamic error).
type InvalidPathTemplData struct {
	agenorTemplData
	// Path is the invalid path
	Path string
}

// Message creates a new i18n message using the template data.
func (td InvalidPathTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-path.dynamic-error",
		Description: "invalid path (dynamic error)",
		Other:       "path: '{{.Path}}'",
	}
}

// InvalidPathError invalid path (dynamic error).
type InvalidPathError struct {
	li18ngo.LocalisableError
	Path string
}

// NewInvalidPathError creates a new InvalidPathError.
func NewInvalidPathError(path string) error {
	return &InvalidPathError{
		LocalisableError: li18ngo.LocalisableError{
			Data: InvalidPathTemplData{
				Path: path,
			},
		},
		Path: path,
	}
}

// =============================================================================
// ❌ InvalidResumeStrategy
//
// InvalidResumeStrategy indicates that the resume strategy supplied by the
// caller is not one of the accepted values.
// =============================================================================

// InvalidResumeStrategyErrorTemplData invalid resume strategy type.
type InvalidResumeStrategyErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InvalidResumeStrategyErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-resume-strategy.static-error",
		Description: "invalid resume strategy type",
		Other:       "invalid resume strategy, must be one of: [spawn, fast]",
	}
}

// InvalidResumeStrategyError invalid resume strategy type.
type InvalidResumeStrategyError struct {
	li18ngo.LocalisableError
}

// ErrInvalidResumeStrategy is the exported sentinel error for
// InvalidResumeStrategyError.
var ErrInvalidResumeStrategy = InvalidResumeStrategyError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InvalidResumeStrategyErrorTemplData{},
	},
}

// =============================================================================
// ❌ InvalidSamplingSpecMissingDirectories
//
// InvalidSamplingSpecMissingDirectories indicates that the file sampling
// specification is invalid because the required number-of-directories field is
// absent.
// =============================================================================

// InvalidSamplingSpecMissingDirectoriesErrorTemplData invalid file sampling
// specification, missing no of directories.
type InvalidSamplingSpecMissingDirectoriesErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InvalidSamplingSpecMissingDirectoriesErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-file-sampling-spec-missing-directories.static-error",
		Description: "invalid file sampling specification, missing no of directories",
		Other:       "invalid file sampling specification, missing no of directories",
	}
}

// InvalidSamplingSpecMissingDirectoriesError invalid file sampling
// specification, missing no of directories.
type InvalidSamplingSpecMissingDirectoriesError struct {
	li18ngo.LocalisableError
}

// ErrInvalidSamplingSpecMissingDirectories is the exported sentinel error for
// InvalidSamplingSpecMissingDirectoriesError.
var ErrInvalidSamplingSpecMissingDirectories = InvalidSamplingSpecMissingDirectoriesError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InvalidSamplingSpecMissingDirectoriesErrorTemplData{},
	},
}

// =============================================================================
// ❌ InvalidSubscription
//
// InvalidSubscription indicates that the subscription type supplied by the
// caller is not one of the accepted values.
// =============================================================================

// InvalidSubscriptionErrorTemplData invalid subscription type.
type InvalidSubscriptionErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InvalidSubscriptionErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-subscription.static-error",
		Description: "invalid subscription type",
		Other:       "invalid subscription type, must be one of: [files, dirs, all]",
	}
}

// InvalidSubscriptionError invalid subscription type.
type InvalidSubscriptionError struct {
	li18ngo.LocalisableError
}

// ErrInvalidSubscription is the exported sentinel error for
// InvalidSubscriptionError.
var ErrInvalidSubscription = InvalidSubscriptionError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InvalidSubscriptionErrorTemplData{},
	},
}

// =============================================================================
// ❌ MissingCustomFilterDefinition
//
// MissingCustomFilterDefinition indicates that the traversal configuration
// references a custom filter but no definition for it was found.
// =============================================================================

// MissingCustomFilterDefinitionErrorTemplData config error
// missing-custom-filter-definition.
type MissingCustomFilterDefinitionErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td MissingCustomFilterDefinitionErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "missing-custom-filter-definition.static-error",
		Description: "config error missing-custom-filter-definition",
		Other:       "missing custom filter definition (config error)",
	}
}

// MissingCustomFilterDefinitionError config error
// missing-custom-filter-definition.
type MissingCustomFilterDefinitionError struct {
	li18ngo.LocalisableError
}

// ErrMissingCustomFilterDefinition is the exported sentinel error for
// MissingCustomFilterDefinitionError.
var ErrMissingCustomFilterDefinition = MissingCustomFilterDefinitionError{
	LocalisableError: li18ngo.LocalisableError{
		Data: MissingCustomFilterDefinitionErrorTemplData{},
	},
}

// =============================================================================
// ❌ PolyFilterIsInvalid
//
// PolyFilterIsInvalid indicates that a poly filter definition fails validation.
// =============================================================================

// PolyFilterIsInvalidErrorTemplData poly filter definition is invalid error.
type PolyFilterIsInvalidErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td PolyFilterIsInvalidErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "poly-filter-is-invalid.static-error",
		Description: "poly filter definition is invalid error",
		Other:       "poly filter definition is invalid",
	}
}

// PolyFilterIsInvalidError poly filter definition is invalid error.
type PolyFilterIsInvalidError struct {
	li18ngo.LocalisableError
}

// ErrPolyFilterIsInvalid is the exported sentinel error for
// PolyFilterIsInvalidError.
var ErrPolyFilterIsInvalid = PolyFilterIsInvalidError{
	LocalisableError: li18ngo.LocalisableError{
		Data: PolyFilterIsInvalidErrorTemplData{},
	},
}

// =============================================================================
// ❌ ResumeFsMismatch
//
// ResumeFsMismatch indicates that the filesystem passed to a resume operation
// does not match the filesystem recorded at the point the session was saved.
// =============================================================================

// ResumeFsMismatchErrorTemplData resume fs mismatch error.
type ResumeFsMismatchErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td ResumeFsMismatchErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "resume-fs-mismatch.static-error",
		Description: "resume fs mismatch error",
		Other:       "resume-fs mismatch",
	}
}

// ResumeFsMismatchError resume fs mismatch error.
type ResumeFsMismatchError struct {
	li18ngo.LocalisableError
}

// ErrResumeFsMismatch is the exported sentinel error for ResumeFsMismatchError.
var ErrResumeFsMismatch = ResumeFsMismatchError{
	LocalisableError: li18ngo.LocalisableError{
		Data: ResumeFsMismatchErrorTemplData{},
	},
}

// =============================================================================
// ❌ TraversalNotSaved
//
// Traversal state not saved as a result of a panic occurring during traversal
// =============================================================================

// TraversalNotSavedTemplData Error returned when a panic occurs during
// traversal and save of the traversal state fails.
type TraversalNotSavedTemplData struct {
	agenorTemplData
	// SavedTo The path the traversal state was attempted to be saved to
	SavedTo string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td TraversalNotSavedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "traversal-not-saved.dynamic-error",
		Description: "Error returned when a panic occurs during traversal and save of the traversal state fails",
		Other:       "'{{.Wrapped}}' Failed to save traversal state to: '{{.SavedTo}}' ",
	}
}

// TraversalNotSavedError Error returned when a panic occurs during traversal
// and save of the traversal state fails.
type TraversalNotSavedError struct {
	li18ngo.LocalisableError
	Wrapped error
	SavedTo string
}

// Error returns the combined wrapped and localised error message.
func (e TraversalNotSavedError) Error() string {
	return fmt.Sprintf("%v, %v", e.Wrapped.Error(), li18ngo.Text(e.Data))
}

// Unwrap returns the wrapped error.
func (e TraversalNotSavedError) Unwrap() error {
	return e.Wrapped
}

// NewTraversalNotSavedError creates a new TraversalNotSavedError wrapping
// wrapped.
func NewTraversalNotSavedError(wrapped error, savedTo string) error {
	return &TraversalNotSavedError{
		LocalisableError: li18ngo.LocalisableError{
			Data: TraversalNotSavedTemplData{
				SavedTo: savedTo,
				Wrapped: wrapped.Error(),
			},
		},
		Wrapped: wrapped,
		SavedTo: savedTo,
	}
}

// =============================================================================
// ❌ TraversalSaved
//
// Traversal state saved as a result of a panic occurring during traversal
// =============================================================================

// TraversalSavedTemplData Error returned when a panic occurs during traversal
// and save of the traversal state succeeds.
type TraversalSavedTemplData struct {
	agenorTemplData
	// SavedTo The path the traversal state was saved to
	SavedTo string
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td TraversalSavedTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "traversal-saved.dynamic-error",
		Description: "Error returned when a panic occurs during traversal and save of the traversal state succeeds",
		Other:       "'{{.Wrapped}}' Traversal state saved successfully to: '{{.SavedTo}}' ",
	}
}

// TraversalSavedError Error returned when a panic occurs during traversal and
// save of the traversal state succeeds.
type TraversalSavedError struct {
	li18ngo.LocalisableError
	Wrapped error
	SavedTo string
}

// Error returns the combined wrapped and localised error message.
func (e TraversalSavedError) Error() string {
	return fmt.Sprintf("%v, %v", e.Wrapped.Error(), li18ngo.Text(e.Data))
}

// Unwrap returns the wrapped error.
func (e TraversalSavedError) Unwrap() error {
	return e.Wrapped
}

// NewTraversalSavedError creates a new TraversalSavedError wrapping wrapped.
func NewTraversalSavedError(wrapped error, savedTo string) error {
	return &TraversalSavedError{
		LocalisableError: li18ngo.LocalisableError{
			Data: TraversalSavedTemplData{
				SavedTo: savedTo,
				Wrapped: wrapped.Error(),
			},
		},
		Wrapped: wrapped,
		SavedTo: savedTo,
	}
}

// =============================================================================
// ❌ TraverseFsMismatch
//
// TraverseFsMismatch indicates that the filesystem passed to the traversal does
// not match the filesystem recorded at the point the session was saved.
// =============================================================================

// TraverseFsMismatchErrorTemplData traverse fs mismatch error.
type TraverseFsMismatchErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td TraverseFsMismatchErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "traverse-fs-mismatch.static-error",
		Description: "traverse fs mismatch error",
		Other:       "traverse-fs mismatch",
	}
}

// TraverseFsMismatchError traverse fs mismatch error.
type TraverseFsMismatchError struct {
	li18ngo.LocalisableError
}

// ErrTraverseFsMismatch is the exported sentinel error for
// TraverseFsMismatchError.
var ErrTraverseFsMismatch = TraverseFsMismatchError{
	LocalisableError: li18ngo.LocalisableError{
		Data: TraverseFsMismatchErrorTemplData{},
	},
}

// =============================================================================
// ❌ UnEqualJSONConversion
//
// UnEqualJSONConversion indicates that a round-trip JSON conversion produced a
// result that does not equal the original value.
// =============================================================================

// UnEqualJSONConversionErrorTemplData JSON options conversion error.
type UnEqualJSONConversionErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UnEqualJSONConversionErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "un-equal-conversion.sentinel-error",
		Description: "JSON options conversion error",
		Other:       "unequal JSON conversion",
	}
}

// UnEqualJSONConversionError JSON options conversion error.
// Use errors.Is(err, locale.ErrUnEqualJSONConversion) to test for this error.
type UnEqualJSONConversionError struct {
	li18ngo.LocalisableError
}

// ErrUnEqualJSONConversion is the exported sentinel for
// UnEqualJSONConversionError.
var ErrUnEqualJSONConversion = UnEqualJSONConversionError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UnEqualJSONConversionErrorTemplData{},
	},
}

// =============================================================================
// ❌ UnsupportedFormat
//
// UnsupportedFormat indicates that the configuration format requested by the
// caller has not been registered with the format registry.
// =============================================================================

// UnsupportedFormatTemplData Error returned when an unregistered config format
// is requested.
type UnsupportedFormatTemplData struct {
	agenorTemplData
	// Format is the unsupported format
	Format string
}

// Message creates a new i18n message using the template data.
func (td UnsupportedFormatTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "unsupported-format.jaywalk.dynamic-error",
		Description: "Error returned when an unregistered config format is requested",
		Other:       "unsupported format '{{.Format}}'",
	}
}

// UnsupportedFormatError Error returned when an unregistered config format is
// requested.
type UnsupportedFormatError struct {
	li18ngo.LocalisableError
	Format string
}

// NewUnsupportedFormatError creates a new UnsupportedFormatError.
func NewUnsupportedFormatError(format string) error {
	return &UnsupportedFormatError{
		LocalisableError: li18ngo.LocalisableError{
			Data: UnsupportedFormatTemplData{
				Format: format,
			},
		},
		Format: format,
	}
}

// =============================================================================
// ❌ UsageMissingHandler
//
// UsageMissingHandler indicates that the command was invoked without
// registering a required handler.
// =============================================================================

// UsageMissingHandlerErrorTemplData usage missing handler.
type UsageMissingHandlerErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UsageMissingHandlerErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "usage-missing-handler.static-error",
		Description: "usage missing handler",
		Other:       "usage missing handler",
	}
}

// UsageMissingHandlerError usage missing handler.
type UsageMissingHandlerError struct {
	li18ngo.LocalisableError
}

// ErrUsageMissingHandler is the exported sentinel error for
// UsageMissingHandlerError.
var ErrUsageMissingHandler = UsageMissingHandlerError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UsageMissingHandlerErrorTemplData{},
	},
}

// =============================================================================
// ❌ UsageMissingRestorePath
//
// UsageMissingRestorePath indicates that the command was invoked without the
// required restore path argument.
// =============================================================================

// UsageMissingRestorePathErrorTemplData usage missing restore path.
type UsageMissingRestorePathErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UsageMissingRestorePathErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "usage-missing-restore-path.static-error",
		Description: "usage missing restore path",
		Other:       "usage missing restore path",
	}
}

// UsageMissingRestorePathError usage missing restore path.
type UsageMissingRestorePathError struct {
	li18ngo.LocalisableError
}

// ErrUsageMissingRestorePath is the exported sentinel error for
// UsageMissingRestorePathError.
var ErrUsageMissingRestorePath = UsageMissingRestorePathError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UsageMissingRestorePathErrorTemplData{},
	},
}

// =============================================================================
// ❌ UsageMissingSubscription
//
// UsageMissingSubscription indicates that the command was invoked without
// specifying a subscription type.
// =============================================================================

// UsageMissingSubscriptionErrorTemplData usage missing subscription.
type UsageMissingSubscriptionErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UsageMissingSubscriptionErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "usage-missing-subscription.static-error",
		Description: "usage missing subscription",
		Other:       "usage missing subscription",
	}
}

// UsageMissingSubscriptionError usage missing subscription.
type UsageMissingSubscriptionError struct {
	li18ngo.LocalisableError
}

// ErrUsageMissingSubscription is the exported sentinel error for
// UsageMissingSubscriptionError.
var ErrUsageMissingSubscription = UsageMissingSubscriptionError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UsageMissingSubscriptionErrorTemplData{},
	},
}

// =============================================================================
// ❌ UsageMissingTreePath
//
// UsageMissingTreePath indicates that the command was invoked without the
// required tree path argument.
// =============================================================================

// UsageMissingTreePathErrorTemplData usage missing tree path.
type UsageMissingTreePathErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td UsageMissingTreePathErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "usage-missing-tree-path.static-error",
		Description: "usage missing tree path",
		Other:       "usage missing tree path",
	}
}

// UsageMissingTreePathError usage missing tree path.
type UsageMissingTreePathError struct {
	li18ngo.LocalisableError
}

// ErrUsageMissingTreePath is the exported sentinel error for
// UsageMissingTreePathError.
var ErrUsageMissingTreePath = UsageMissingTreePathError{
	LocalisableError: li18ngo.LocalisableError{
		Data: UsageMissingTreePathErrorTemplData{},
	},
}

// =============================================================================
// ❌ WorkerPoolCreationFailed
//
// WorkerPoolCreationFailed indicates that the worker pool could not be
// initialised.
// =============================================================================

// WorkerPoolCreationFailedErrorTemplData failed to create worker pool.
type WorkerPoolCreationFailedErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td WorkerPoolCreationFailedErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "failed-to-create-worker-pool.static-error",
		Description: "failed to create worker pool",
		Other:       "failed to create worker pool",
	}
}

// WorkerPoolCreationFailedError failed to create worker pool.
type WorkerPoolCreationFailedError struct {
	li18ngo.LocalisableError
}

// ErrWorkerPoolCreationFailed is the exported sentinel error for
// WorkerPoolCreationFailedError.
var ErrWorkerPoolCreationFailed = WorkerPoolCreationFailedError{
	LocalisableError: li18ngo.LocalisableError{
		Data: WorkerPoolCreationFailedErrorTemplData{},
	},
}
