// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 🧊 QueryCmdLongDesc
//
// QueryCmdLongDesc is the long description shown in cobra help output for the
// nav command.
// =============================================================================

// QueryCmdLongDescTemplData query acts as a non destructive directory tree
// inquiry.
type QueryCmdLongDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for QueryCmdLongDescTemplData.
func (td QueryCmdLongDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "query-command-long-description",
		Description: "query acts as a non destructive directory tree inquiry",
		Other:       "query command walks the directory tree showing nodes that  satisfy filtering criteria when present. Can be used as a kind of dry run traversal, except no actions or pipelines are invoked as in the case for walk and sprint commands.",
	}
}

// =============================================================================
// 🧊 QueryCmdShortDesc
//
// QueryCmdShortDesc is the short description shown in cobra help output for the
// query command.
// =============================================================================

// QueryCmdShortDescTemplData query acts as a non destructive directory tree
// inquiry.
type QueryCmdShortDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for QueryCmdShortDescTemplData.
func (td QueryCmdShortDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "query-command-short-description",
		Description: "query acts as a non destructive directory tree inquiry",
		Other:       "query navigates the directory tree via a walk traversal",
	}
}
