// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 🧊 RootCmdConfigFileUsage
//
// RootCmdConfigFileUsage is the usage string for the config file flag on the
// root command.
// =============================================================================

// RootCmdConfigFileUsageTemplData root command config flag usage.
type RootCmdConfigFileUsageTemplData struct {
	agenorTemplData
	// ConfigFileName is the base name of the config file without extension
	ConfigFileName string
}

// Message returns the i18n message for RootCmdConfigFileUsageTemplData.
func (td RootCmdConfigFileUsageTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "root-command-config-file-usage",
		Description: "root command config flag usage",
		Other:       "Config file (default is $HOME/{{.ConfigFileName}}.yml)",
	}
}

// NewRootCmdConfigFileUsageTemplData creates a new
// RootCmdConfigFileUsageTemplData.
func NewRootCmdConfigFileUsageTemplData(configFileName string) RootCmdConfigFileUsageTemplData {
	return RootCmdConfigFileUsageTemplData{
		agenorTemplData: agenorTemplData{},
		ConfigFileName:  configFileName,
	}
}

// =============================================================================
// 🧊 RootCmdLangUsage
//
// RootCmdLangUsage is the usage string for the language flag on the root
// command.
// =============================================================================

// RootCmdLangUsageTemplData root command lang usage.
type RootCmdLangUsageTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for RootCmdLangUsageTemplData.
func (td RootCmdLangUsageTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "root-command-language-usage",
		Description: "root command lang usage",
		Other:       "'lang' defines the language according to IETF BCP 47",
	}
}

// =============================================================================
// 🧊 RootCmdLongDesc
//
// RootCmdLongDesc is the long description shown in cobra help output for the
// root command.
// =============================================================================

// RootCmdLongDescTemplData Navigates a directory tree and shows matching nodes.
type RootCmdLongDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for RootCmdLongDescTemplData.
func (td RootCmdLongDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "root-command-long-description",
		Description: "Navigates a directory tree and shows matching nodes",
		Other: `Navigates a directory tree and shows matching nodes. The root command
does not take any action for each visited node. It is simply a visualiser for
traversal.`,
	}
}

// =============================================================================
// 🧊 RootCmdShortDesc
//
// RootCmdShortDesc is the short description shown in cobra help output for the
// root command.
// =============================================================================

// RootCmdShortDescTemplData Navigates a directory tree.
type RootCmdShortDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for RootCmdShortDescTemplData.
func (td RootCmdShortDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "root-command-short-description",
		Description: "Navigates a directory tree",
		Other:       "Navigates a directory tree",
	}
}
