// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 🧊 RunCmdLongDesc
//
// RunCmdLongDesc is the long description shown in cobra help output for the run
// command.
// =============================================================================

// RunCmdLongDescTemplData Navigates a directory tree on multiple single cpu
// cores and executes actions and pipelines for matching nodes.
type RunCmdLongDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for RunCmdLongDescTemplData.
func (td RunCmdLongDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "run-command-long-description",
		Description: "Navigates a directory tree on multiple single cpu cores and executes actions and pipelines for matching nodes",
		Other: `Navigates a directory tree and executes actions and pipelines for 
matching nodes. All actions are executed concurrently on multiple
cpu cores. All available cpu cores can be utilised by specifying
the --cpu flag, or a specific set of cores can be targeted using
the --now flag. The run command is designed to be run when bulk
processing of a directory tree is required where the configured
action is heavily IO bound. Actions and pipelines defined for walk
run in the same way as they do for run.
Use --action or --pipeline to name a config-defined operation.
`,
	}
}

// =============================================================================
// 🧊 RunCmdShortDesc
//
// RootCmdShortDesc is the short description shown in cobra help output for the
// root command.
// =============================================================================

// RunCmdShortDescTemplData Navigates a directory tree on a single cpu core.
type RunCmdShortDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for RunCmdShortDescTemplData.
func (td RunCmdShortDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "run-command-short-description",
		Description: "Navigates a directory tree on a single cpu core",
		Other:       "Executes actions and pipelines for matching nodes on a single cpu core",
	}
}
