// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ InvalidFileSamplingSpecMissingFiles
//
// InvalidFileSamplingSpecMissingFiles indicates that the file sampling
// specification is invalid because the required number-of-files field is
// absent.
// =============================================================================

// InvalidFileSamplingSpecMissingFilesErrorTemplData invalid file sampling
// specification, missing no of files.
type InvalidFileSamplingSpecMissingFilesErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InvalidFileSamplingSpecMissingFilesErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-file-sampling-spec-missing-files.static-error",
		Description: "invalid file sampling specification, missing no of files",
		Other:       "Invalid file sampling specification, missing no of files",
	}
}

// InvalidFileSamplingSpecMissingFilesError invalid file sampling specification,
// missing no of files.
type InvalidFileSamplingSpecMissingFilesError struct {
	li18ngo.LocalisableError
}

// ErrInvalidFileSamplingSpecMissingFiles is the exported sentinel error for
// InvalidFileSamplingSpecMissingFilesError.
var ErrInvalidFileSamplingSpecMissingFiles = InvalidFileSamplingSpecMissingFilesError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InvalidFileSamplingSpecMissingFilesErrorTemplData{},
	},
}

// =============================================================================
// ❌ InvalidSamplingSpecMissingDirectories
//
// InvalidSamplingSpecMissingDirectories indicates that the file sampling
// specification is invalid because the required number-of-directories field is
// absent.
// =============================================================================

// InvalidSamplingSpecMissingDirectoriesErrorTemplData invalid file sampling
// specification, missing no of directories.
type InvalidSamplingSpecMissingDirectoriesErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td InvalidSamplingSpecMissingDirectoriesErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "invalid-file-sampling-spec-missing-directories.static-error",
		Description: "invalid file sampling specification, missing no of directories",
		Other:       "Invalid file sampling specification, missing no of directories",
	}
}

// InvalidSamplingSpecMissingDirectoriesError invalid file sampling
// specification, missing no of directories.
type InvalidSamplingSpecMissingDirectoriesError struct {
	li18ngo.LocalisableError
}

// ErrInvalidSamplingSpecMissingDirectories is the exported sentinel error for
// InvalidSamplingSpecMissingDirectoriesError.
var ErrInvalidSamplingSpecMissingDirectories = InvalidSamplingSpecMissingDirectoriesError{
	LocalisableError: li18ngo.LocalisableError{
		Data: InvalidSamplingSpecMissingDirectoriesErrorTemplData{},
	},
}
