// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"fmt"
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ CmdNotFoundAsPathBinaryOrBuiltin
//
// Error returned when a command specified in the config is not found in the
// current environment as PATH binary or cmd.exe builtin
// =============================================================================

// CmdNotFoundAsPathBinaryOrBuiltinTemplData Command not found in environment as
// a PATH binary or cmd.exe builtin error.
type CmdNotFoundAsPathBinaryOrBuiltinTemplData struct {
	agenorTemplData
	// Command The command that was not found
	Command string
}

// Message creates a new i18n message using the template data.
func (td CmdNotFoundAsPathBinaryOrBuiltinTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "cmd-not-found-as-path-binary-or-builtin.dynamic-error",
		Description: "Command not found in environment as a PATH binary or cmd.exe builtin error",
		Other:       "'{{.Command}}' Not found in current environment",
	}
}

// CmdNotFoundAsPathBinaryOrBuiltinError Command not found in environment as a
// PATH binary or cmd.exe builtin error.
type CmdNotFoundAsPathBinaryOrBuiltinError struct {
	li18ngo.LocalisableError
	CmdNotFoundAsPathBinaryOrBuiltinTemplData
}

// NewCmdNotFoundAsPathBinaryOrBuiltinError creates a new
// CmdNotFoundAsPathBinaryOrBuiltinError.
func NewCmdNotFoundAsPathBinaryOrBuiltinError(command string) error {
	td := CmdNotFoundAsPathBinaryOrBuiltinTemplData{
		agenorTemplData: agenorTemplData{},
		Command:         command,
	}
	return &CmdNotFoundAsPathBinaryOrBuiltinError{
		LocalisableError: li18ngo.LocalisableError{Data: td},
		CmdNotFoundAsPathBinaryOrBuiltinTemplData: td,
	}
}

// =============================================================================
// ❌ CmdNotFoundInEnv
//
// Error returned when a command specified in the config is not found in the
// current environment
// =============================================================================

// CmdNotFoundInEnvTemplData Command not found in environment error.
type CmdNotFoundInEnvTemplData struct {
	agenorTemplData
	// Command The command that was not found
	Command string
}

// Message creates a new i18n message using the template data.
func (td CmdNotFoundInEnvTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "cmd-not-found-in-env.dynamic-error",
		Description: "Command not found in environment error",
		Other:       "'{{.Command}}' Not found in current environment",
	}
}

// CmdNotFoundInEnvError Command not found in environment error.
type CmdNotFoundInEnvError struct {
	li18ngo.LocalisableError
	CmdNotFoundInEnvTemplData
}

// NewCmdNotFoundInEnvError creates a new CmdNotFoundInEnvError.
func NewCmdNotFoundInEnvError(command string) error {
	td := CmdNotFoundInEnvTemplData{
		agenorTemplData: agenorTemplData{},
		Command:         command,
	}
	return &CmdNotFoundInEnvError{
		LocalisableError:          li18ngo.LocalisableError{Data: td},
		CmdNotFoundInEnvTemplData: td,
	}
}

// =============================================================================
// ❌ NeitherPwshOrPowerShellExeFound
//
// neither pwsh.exe nor powershell.exe found on PATH
// =============================================================================

// NeitherPwshOrPowerShellExeFoundErrorTemplData neither pwsh.exe nor
// powershell.exe found on PATH.
type NeitherPwshOrPowerShellExeFoundErrorTemplData struct {
	agenorTemplData
}

// Message creates a new i18n message using the template data.
func (td NeitherPwshOrPowerShellExeFoundErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "neither-pwsh-or-powershell-exe-found.static-error",
		Description: "neither pwsh.exe nor powershell.exe found on PATH",
		Other:       "Neither pwsh.exe nor powershell.exe found on PATH",
	}
}

// NeitherPwshOrPowerShellExeFoundError neither pwsh.exe nor powershell.exe
// found on PATH.
type NeitherPwshOrPowerShellExeFoundError struct {
	li18ngo.LocalisableError
}

// ErrNeitherPwshOrPowerShellExeFound is the exported sentinel error for
// NeitherPwshOrPowerShellExeFoundError.
var ErrNeitherPwshOrPowerShellExeFound = NeitherPwshOrPowerShellExeFoundError{
	LocalisableError: li18ngo.LocalisableError{
		Data: NeitherPwshOrPowerShellExeFoundErrorTemplData{},
	},
}

// =============================================================================
// ❌ PSMSetNoPowerShellExeFound
//
// PSModulePath is set but no PowerShell executable found
// =============================================================================

// PSMSetNoPowerShellExeFoundErrorTemplData PSModulePath is set but no
// PowerShell executable found.
type PSMSetNoPowerShellExeFoundErrorTemplData struct {
	agenorTemplData
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td PSMSetNoPowerShellExeFoundErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "psm-set-no-powershell-exe-found.static-error",
		Description: "PSModulePath is set but no PowerShell executable found",
		Other:       "PSModulePath is set but no PowerShell executable found: '{{.Wrapped}}'",
	}
}

// PSMSetNoPowerShellExeFoundError PSModulePath is set but no PowerShell
// executable found.
type PSMSetNoPowerShellExeFoundError struct {
	li18ngo.LocalisableError
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e PSMSetNoPowerShellExeFoundError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e PSMSetNoPowerShellExeFoundError) Unwrap() error {
	return e.wrapped
}

// NewPSMSetNoPowerShellExeFoundError creates a new
// PSMSetNoPowerShellExeFoundError wrapping wrapped.
func NewPSMSetNoPowerShellExeFoundError(wrapped error) error {
	return &PSMSetNoPowerShellExeFoundError{
		LocalisableError: li18ngo.LocalisableError{
			Data: PSMSetNoPowerShellExeFoundErrorTemplData{Wrapped: wrapped.Error()},
		},
		wrapped: wrapped,
	}
}
