// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 🧊 SprintCmdLongDesc
//
// SprintCmdLongDesc is the long description shown in cobra help output for the
// sprint command.
// =============================================================================

// SprintCmdLongDescTemplData Navigates a directory tree on multiple single cpu
// cores and executes actions and pipelines for matching nodes.
type SprintCmdLongDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for SprintCmdLongDescTemplData.
func (td SprintCmdLongDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "sprint-command-long-description",
		Description: "Navigates a directory tree on multiple single cpu cores and executes actions and pipelines for matching nodes",
		Other: `Navigates a directory tree and executes actions and pipelines for 
matching nodes. All actions are executed concurrently on multiple
cpu cores. All available cpu cores can be utilised by specifying
the --cpu flag, or a specific set of cores can be targeted using
the --now flag. The sprint command is designed to be run when bulk
processing of a directory tree is required where the configured
action is heavily IO bound. Actions and pipelines defined for walk
run in the same way as they do for sprint.
Use --action or --pipeline to name a config-defined operation.
`,
	}
}

// =============================================================================
// 🧊 SprintCmdShortDesc
//
// RootCmdShortDesc is the short description shown in cobra help output for the
// root command.
// =============================================================================

// SprintCmdShortDescTemplData Navigates a directory tree on a single cpu core.
type SprintCmdShortDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for SprintCmdShortDescTemplData.
func (td SprintCmdShortDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "sprint-command-short-description",
		Description: "Navigates a directory tree on a single cpu core",
		Other:       "Executes actions and pipelines for matching nodes on a single cpu core",
	}
}
