// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 🧊 WalkCmdLongDesc
//
// WalkCmdLongDesc is the long description shown in cobra help output for the
// walk command.
// =============================================================================

// WalkCmdLongDescTemplData Navigates a directory tree on a single cpu core and
// executes actions and pipelines for matching nodes.
type WalkCmdLongDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for WalkCmdLongDescTemplData.
func (td WalkCmdLongDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "walk-command-long-description",
		Description: "Navigates a directory tree on a single cpu core and executes actions and pipelines for matching nodes",
		Other: `Navigates a directory tree and executes actions and pipelines for 
matching nodes. All actions are executed sequentially on a
single cpu core. This is the simplest and most compatible
execution mode, but may be slower for large traversals, depending
on the configured actions and pipelines. Actions support invocation
of any external command found on PATH, shell built-in function or
script.
Use --action or --pipeline to name a config-defined operation.
`,
	}
}

// =============================================================================
// 🧊 WalkCmdShortDesc
//
// RootCmdShortDesc is the short description shown in cobra help output for the
// root command.
// =============================================================================

// WalkCmdShortDescTemplData Navigates a directory tree on a single cpu core.
type WalkCmdShortDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for WalkCmdShortDescTemplData.
func (td WalkCmdShortDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "walk-command-short-description",
		Description: "Navigates a directory tree on a single cpu core",
		Other:       "Executes actions and pipelines for matching nodes on a single cpu core",
	}
}
