// Code generated by "stringer -type=ConfigFormat -linecomment -trimprefix=ConfigFormat -output config-format-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfigFormatYaml-0]
	_ = x[ConfigFormatJson-1]
}

const _ConfigFormat_name = "config-format-yamlconfig-format-json"

var _ConfigFormat_index = [...]uint8{0, 18, 36}

func (i ConfigFormat) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ConfigFormat_index)-1 {
		return "ConfigFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConfigFormat_name[_ConfigFormat_index[idx]:_ConfigFormat_index[idx+1]]
}
