// Code generated by "stringer -type=EntryType -linecomment -trimprefix=EntryType -output entry-type-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntryTypeDirectory-0]
	_ = x[EntryTypeFile-1]
	_ = x[EntryTypeAll-2]
}

const _EntryType_name = "directory-entryfile-entryall-entries"

var _EntryType_index = [...]uint8{0, 15, 25, 36}

func (i EntryType) String() string {
	if i >= EntryType(len(_EntryType_index)-1) {
		return "EntryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntryType_name[_EntryType_index[i]:_EntryType_index[i+1]]
}
