// Code generated by "stringer -type=GlobExtraction -linecomment -trimprefix=GlobExtraction -output glob-ex-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GlobExtractionUndefined-0]
	_ = x[GlobExtractionStarDot-1]
	_ = x[GlobExtractionStarOnly-2]
	_ = x[GlobExtractionLeadingDotOnly-3]
	_ = x[GlobExtractionBare-4]
}

const _GlobExtraction_name = "undefinedstar-dotstar-onlyleading-dot-onlybare"

var _GlobExtraction_index = [...]uint8{0, 9, 17, 26, 42, 46}

func (i GlobExtraction) String() string {
	if i >= GlobExtraction(len(_GlobExtraction_index)-1) {
		return "GlobExtraction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GlobExtraction_name[_GlobExtraction_index[i]:_GlobExtraction_index[i+1]]
}
