// Code generated by "stringer -type=Hibernation -linecomment -trimprefix=Hibernation -output hibernation-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HibernationUndefined-0]
	_ = x[HibernationPending-1]
	_ = x[HibernationActive-2]
	_ = x[HibernationRetired-3]
}

const _Hibernation_name = "undefinedpending-hibernationactive-hibernationretired-hibernation"

var _Hibernation_index = [...]uint8{0, 9, 28, 46, 65}

func (i Hibernation) String() string {
	if i >= Hibernation(len(_Hibernation_index)-1) {
		return "Hibernation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Hibernation_name[_Hibernation_index[i]:_Hibernation_index[i+1]]
}
