// Code generated by "stringer -type=Metric -linecomment -trimprefix=Metric -output metric-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MetricNoFilesInvoked-1]
	_ = x[MetricNoFilesFilteredOut-2]
	_ = x[MetricNoDirectoriesInvoked-3]
	_ = x[MetricNoDirectoriesFilteredOut-4]
	_ = x[MetricNoChildFilesFound-5]
	_ = x[MetricNoChildFilesFilteredOut-6]
}

const _Metric_name = "metric-no-of-filesmetric-no-of-files-filtered-outmetric-no-of-directoriesmetric-no-of-directories-filtered-outmetric-no-of-child-files-foundmetric-no-of-child-files-found"

var _Metric_index = [...]uint8{0, 18, 49, 73, 110, 140, 170}

func (i Metric) String() string {
	i -= 1
	if i >= Metric(len(_Metric_index)-1) {
		return "Metric(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Metric_name[_Metric_index[i]:_Metric_index[i+1]]
}
