// Code generated by "stringer -type=PersistenceFormat -linecomment -trimprefix=Persist -output persistence-format-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PersistUndefined-0]
	_ = x[PersistJSON-1]
}

const _PersistenceFormat_name = "persistence-undefinedpersist-json"

var _PersistenceFormat_index = [...]uint8{0, 21, 33}

func (i PersistenceFormat) String() string {
	if i >= PersistenceFormat(len(_PersistenceFormat_index)-1) {
		return "PersistenceFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PersistenceFormat_name[_PersistenceFormat_index[i]:_PersistenceFormat_index[i+1]]
}
