// Code generated by "stringer -type=SampleType -linecomment -trimprefix=SampleType -output sample-type-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SampleTypeUndefined-0]
	_ = x[SampleTypeSlice-1]
	_ = x[SampleTypeFilter-2]
	_ = x[SampleTypeCustom-3]
}

const _SampleType_name = "undefined-sampleslice-samplefilter-samplecustom-sample"

var _SampleType_index = [...]uint8{0, 16, 28, 41, 54}

func (i SampleType) String() string {
	if i >= SampleType(len(_SampleType_index)-1) {
		return "SampleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SampleType_name[_SampleType_index[i]:_SampleType_index[i+1]]
}
