// Code generated by "stringer -type=ShellKind -linecomment -trimprefix=ShellKind -output shell-kind-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShellKindNativeUnix-0]
	_ = x[ShellKindPowerShell-1]
	_ = x[ShellKindCmdExe-2]
	_ = x[ShellKindCygwin-3]
	_ = x[ShellKindMSYS2-4]
}

const _ShellKind_name = "native-unixpowershellcmd.execygwinmsys2"

var _ShellKind_index = [...]uint8{0, 11, 21, 28, 34, 39}

func (i ShellKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ShellKind_index)-1 {
		return "ShellKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ShellKind_name[_ShellKind_index[idx]:_ShellKind_index[idx+1]]
}
