// Code generated by "stringer -type=TriStateBool -linecomment -trimprefix=TriStateBool -output tri-state-bool-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TriStateBoolUndefined-0]
	_ = x[TriStateBoolTrue-1]
	_ = x[TriStateBoolFalse-2]
}

const _TriStateBool_name = "undefined-booltruefalse"

var _TriStateBool_index = [...]uint8{0, 14, 18, 23}

func (i TriStateBool) String() string {
	if i >= TriStateBool(len(_TriStateBool_index)-1) {
		return "TriStateBool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TriStateBool_name[_TriStateBool_index[i]:_TriStateBool_index[i+1]]
}
